/* MMT ДВИ v0.10 — единая модель вузов, каталог/сравнение, главная-диспетчер и календарь */
(function setupV010(){
  const ver=document.querySelector('.ver'); if(ver) ver.textContent='v0.10';
  document.title='MMT ДВИ — v0.10';

  state.v10Compare=Array.isArray(state.v10Compare)?state.v10Compare:[];
  state.v10DeadlineDone=state.v10DeadlineDone&&typeof state.v10DeadlineDone==='object'?state.v10DeadlineDone:{};
  state.v10Reminders=state.v10Reminders&&typeof state.v10Reminders==='object'?state.v10Reminders:{};
  state.v10CustomDeadlines=Array.isArray(state.v10CustomDeadlines)?state.v10CustomDeadlines:[];
  state.v10Catalog=state.v10Catalog&&typeof state.v10Catalog==='object'?state.v10Catalog:{query:'',city:'all',format:'all',planOnly:false};

  const css=document.createElement('style');
  css.textContent=`
    .v10hero{background:var(--ink);color:#fff;border-radius:22px;padding:17px;margin:12px 0}.v10hero .meta{color:#bcbcbc}.v10hero .btn{margin-top:10px}
    .v10filters{display:grid;gap:8px;margin:12px 0}.v10filters .input,.v10filters .select{margin:0}.v10filterrow{display:grid;grid-template-columns:1fr 1fr;gap:8px}.v10check{display:flex;gap:8px;align-items:center;padding:10px 2px;font-size:13px}.v10check input{accent-color:var(--o)}
    .uniCard10{background:#fff;border:1px solid var(--line);border-radius:19px;padding:14px;margin:9px 0}.uniCard10.inplan{border-color:var(--o)}.uniCard10 .titleline{display:flex;justify-content:space-between;gap:10px;align-items:flex-start}.uniCard10 h3{margin:0 0 4px}.uniTags10{display:flex;gap:5px;flex-wrap:wrap;margin:9px 0}.uniTags10 span{font-size:10px;padding:6px 8px;border-radius:999px;background:var(--muted)}.uniActions10{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:10px}.uniActions10 .btn{margin:0}.comparePick{display:flex;gap:7px;align-items:center;font-size:12px;margin-top:9px}.comparePick input{accent-color:var(--o)}
    .passport10{background:#fff;border:1px solid var(--line);border-radius:17px;padding:12px;margin:0 0 12px}.passport10 .passportGrid{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:9px}.passport10 .pbox{background:var(--muted);border-radius:12px;padding:9px}.passport10 .pbox small{display:block;color:var(--soft);margin-bottom:3px}.passport10 .pbox b{font-size:12px}
    .compareUni10{background:#fff;border:1px solid var(--line);border-radius:19px;padding:14px;margin:9px 0}.compareField10{display:grid;grid-template-columns:105px 1fr;gap:9px;padding:9px 0;border-bottom:1px solid #eee;font-size:12px}.compareField10:last-child{border:0}.compareField10 span{color:var(--soft)}
    .dash10{border:2px solid var(--o);background:#fff}.dash10 .next10{font:700 20px/1.25 Montserrat,Arial,sans-serif;margin:7px 0}.planChips10{display:flex;gap:6px;flex-wrap:wrap;margin:9px 0}.planChips10 span{background:var(--muted);border-radius:999px;padding:7px 9px;font-size:11px}.attention10{display:grid;gap:7px;margin-top:10px}.attentionItem10{display:grid;grid-template-columns:28px 1fr auto;gap:8px;align-items:center;background:var(--muted);border-radius:13px;padding:10px}.attentionItem10 .ico{width:26px;height:26px;border-radius:9px;background:#fff;display:grid;place-items:center;font-weight:800}.attentionItem10 b{font-size:12px}.attentionItem10 small{display:block;color:var(--soft)}
    .deadline10{background:#fff;border:1px solid var(--line);border-radius:17px;padding:13px;margin:8px 0}.deadline10.done{opacity:.65}.deadline10 .dtop{display:flex;justify-content:space-between;gap:8px;align-items:flex-start}.deadline10 .when{font-weight:800;margin:5px 0}.deadline10 .source{font-size:10px;color:var(--soft);margin-top:7px}.deadlineActions10{display:flex;gap:6px;flex-wrap:wrap;margin-top:9px}.deadlineActions10 .btn{width:auto;margin:0;padding:8px 10px}.archive10{border-left:4px solid #aaa}.customForm10{display:grid;gap:8px}.empty10{background:var(--muted);border-radius:14px;padding:13px;font-size:12px;color:var(--soft)}
    .catalogToolbar10{position:sticky;top:62px;z-index:7;background:var(--bg);padding:7px 0}.compareBar10{display:flex;justify-content:space-between;gap:8px;align-items:center;background:var(--ink);color:#fff;border-radius:15px;padding:10px 12px}.compareBar10 .btn{width:auto;margin:0;padding:8px 10px}
    @media(max-width:370px){.v10filterrow,.uniActions10,.passport10 .passportGrid{grid-template-columns:1fr}.compareField10{grid-template-columns:1fr}}
  `;document.head.appendChild(css);

  function appendScreen(id,html){if(document.getElementById(id))return document.getElementById(id);const s=document.createElement('section');s.id=id;s.className='screen';s.innerHTML=html;document.querySelector('main').appendChild(s);return s}
  function safe(s){return typeof esc==='function'?esc(String(s??'')):String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}

  /* Единый паспорт вуза. Новые экраны должны читать данные отсюда, а не хранить собственную копию. */
  const UNIS={
    spbgikit:{id:'spbgikit',title:'СПбГИКиТ',city:'Санкт-Петербург',program:'42.03.02 Журналистика · «Журналистика в медиаиндустрии»',screen:'uni',prep:'spbgikit',stateKey:'savedUni',cycle:'кампания 2026 · следующая требует проверки',source:'официальные материалы приёма и программа ДВИ',status:'структура заполнена',formats:['письменная работа','коллоквиум'],portfolio:true,budget:'6 мест · очная журналистика · 2026',tuition:'283 000 ₽/год · 2026',model:'письменная + устная + портфолио',deadlineNotes:[
      {id:'spb_docs26',label:'Документы при внутренних испытаниях',when:'10 июля 2026 · 12:00 МСК',action:'Архивная дата кампании 2026. Для следующей кампании дождаться новой официальной даты.',archive:true},
      {id:'spb_exams26',label:'Период внутренних испытаний',when:'21 июня — 25 июля 2026',action:'Архивный ориентир. Перед подготовкой календаря новой кампании заменить актуальными датами.',archive:true}
    ]},
    mpgu:{id:'mpgu',title:'МПГУ',city:'Москва',program:'Журналистика · программа в базе дополняется',screen:'mpgu',prep:'mpguPrep',stateKey:'savedMpgu',cycle:'примеры прошлых заданий · правила дополняются',source:'часть материалов не является официальным источником',status:'нужна дальнейшая верификация',formats:['творческий текст'],portfolio:false,budget:'не внесено',tuition:'не внесено',model:'свободный творческий текст',deadlineNotes:[]},
    ranepa:{id:'ranepa',title:'РАНХиГС',city:'Москва',program:'42.03.02 Журналистика',screen:'ranepa',prep:'ranepaPrep',stateKey:'savedRanepa',cycle:'программа ДВИ · лето 2026',source:'загруженная программа ДВИ',status:'формат внесён · банк тренировок дорабатывается',formats:['письменное тестирование'],portfolio:false,budget:'не внесено',tuition:'не внесено',model:'тестирование · 40 вопросов',deadlineNotes:[]},
    gitr:{id:'gitr',title:'ГИТР',city:'Москва',program:'42.03.02 Журналистика · профиль «телевидение и радио»',screen:'gitr',prep:'gitrOral',stateKey:'savedGitr',cycle:'программа ДВИ 2026',source:'приложение №4 к приказу от 19.01.2026 №61',status:'структура ДВИ внесена',formats:['коллоквиум','эссе'],portfolio:true,budget:'не внесено',tuition:'не внесено',model:'коллоквиум + эссе + творческая папка',deadlineNotes:[
      {id:'gitr_folder_relative',label:'Творческая папка',when:'не менее чем за 3 дня до экзамена',action:'Когда появится дата экзамена нужной кампании, приложение должно автоматически рассчитать крайний день отправки папки.',archive:false}
    ]}
  };
  window.MMT_UNIVERSITIES=UNIS;
  function isPlanned(u){return !!state[u.stateKey]}
  function plannedUnis(){return Object.values(UNIS).filter(isPlanned)}

  /* Унифицированные паспорта поверх старых вузовских экранов. */
  function injectPassports(){Object.values(UNIS).forEach(u=>{const screen=document.getElementById(u.screen);if(!screen||document.getElementById('passport10-'+u.id))return;const p=document.createElement('div');p.id='passport10-'+u.id;p.className='passport10';p.innerHTML=`<div class="row between"><div><b>Паспорт программы</b><div class="meta">единая модель MMT ДВИ</div></div><span id="passPlan-${u.id}" class="status"></span></div><div class="passportGrid"><div class="pbox"><small>Кампания / версия</small><b>${safe(u.cycle)}</b></div><div class="pbox"><small>Статус данных</small><b>${safe(u.status)}</b></div><div class="pbox"><small>Формат ДВИ</small><b>${safe(u.formats.join(' + '))}</b></div><div class="pbox"><small>Источник</small><b>${safe(u.source)}</b></div></div>`;screen.prepend(p)});}

  /* Каталог / поиск / фильтры. */
  appendScreen('uniCatalog',`
    <div class="eye">Вузы · единый каталог</div><div class="row between"><div><h2>Куда поступать</h2><p class="meta">Один формат карточек для всех вузов</p></div><span class="status o">4 модели</span></div>
    <div class="v10hero"><div class="meta">Принцип</div><h3>Сначала сравнить условия. Потом добавить цель в план.</h3><p>Просматривать вуз можно свободно. Персональная подготовка, календарь и готовность включаются после добавления в план.</p></div>
    <div class="v10filters"><input id="v10UniQuery" class="input" placeholder="Вуз, город, программа..."><div class="v10filterrow"><select id="v10City" class="select"><option value="all">Все города</option><option value="Москва">Москва</option><option value="Санкт-Петербург">Санкт-Петербург</option></select><select id="v10Format" class="select"><option value="all">Любой ДВИ</option><option value="oral">Собеседование</option><option value="written">Письменная работа</option><option value="test">Тест</option><option value="portfolio">Портфолио</option></select></div><label class="v10check"><input id="v10PlanOnly" type="checkbox"> Только в моём плане</label></div>
    <div class="catalogToolbar10"><div class="compareBar10"><div><b>Сравнение</b><div class="meta" style="color:#bbb"><span id="v10CompareCount">0</span> из 3 выбрано</div></div><button class="btn small" onclick="openV10Compare()">Сравнить</button></div></div>
    <div id="v10CatalogList"></div>`);

  appendScreen('uniCompare10',`
    <div class="eye">Вузы · сравнение</div><div class="row between"><div><h2>Сравнить программы</h2><p class="meta">До трёх целей одновременно</p></div><span id="compare10Count" class="status o">0</span></div>
    <div class="notice">Сравниваем только то, что уже есть в базе. Отсутствующее значение показываем как «не внесено», а не угадываем.</div><div id="compare10List"></div><button class="btn secondary" data-go="uniCatalog">Изменить выбор</button>`);

  /* Главная как диспетчер. */
  const home=document.getElementById('home');
  if(home&&!document.getElementById('v10Dashboard')){const d=document.createElement('div');d.id='v10Dashboard';d.className='card dash10';home.prepend(d);}

  /* Календарь 2.0. Старый экран сохраняем как оболочку, но содержимое заменяем единым центром. */
  const oldCalendar=document.getElementById('calendar');
  if(oldCalendar) oldCalendar.innerHTML=`<div class="eye">Мой календарь</div><div class="row between"><div><h2>Дедлайны и действия</h2><p class="meta">Только мои вузы + личные даты</p></div><span class="status o">v0.10</span></div><div id="deadlinePlan10"></div><div class="card"><h3>Добавить личную дату</h3><p class="sub">Например: консультация, свой дедлайн черновика, отправка портфолио. Это личное событие, а не официальный срок вуза.</p><div class="customForm10"><input id="customDeadlineTitle10" class="input" placeholder="Что сделать"><input id="customDeadlineDate10" class="input" type="date"><select id="customDeadlineUni10" class="select"></select><button class="btn" onclick="addCustomDeadline10()">Добавить в календарь</button></div></div><div id="customDeadlineList10"></div><div id="archiveDeadlineList10"></div>`;
  else appendScreen('calendar',`<div class="eye">Мой календарь</div><h2>Дедлайны и действия</h2><div id="deadlinePlan10"></div><div id="customDeadlineList10"></div><div id="archiveDeadlineList10"></div>`);

  /* Делаем новые точки входа заметными. */
  document.querySelectorAll('.nav').forEach(n=>{if((n.textContent||'').includes('Вузы')){n.setAttribute('data-go','uniCatalog');n.setAttribute('data-nav','uniCatalog')}});
  const search=document.getElementById('search');if(search&&!document.getElementById('v10CatalogShortcut')){const c=document.createElement('div');c.id='v10CatalogShortcut';c.className='card orange click';c.setAttribute('data-go','uniCatalog');c.innerHTML='<h3>Открыть новый каталог вузов</h3><p class="meta">Поиск · фильтры · сравнение · мой план</p>';search.prepend(c)}
  const results=document.getElementById('results');if(results&&!document.getElementById('v10CompareShortcut')){const b=document.createElement('button');b.id='v10CompareShortcut';b.className='btn';b.setAttribute('data-go','uniCatalog');b.textContent='Поиск и сравнение вузов';results.prepend(b)}

  function formatMatches(u,f){if(f==='all')return true;const s=u.formats.join(' ').toLowerCase();if(f==='oral')return /коллоквиум|собесед/.test(s);if(f==='written')return /письмен|эссе|творческий текст/.test(s);if(f==='test')return /тест/.test(s);if(f==='portfolio')return u.portfolio;return true}
  function renderCatalog10(){const box=document.getElementById('v10CatalogList');if(!box)return;const f=state.v10Catalog;const q=(f.query||'').trim().toLowerCase();const arr=Object.values(UNIS).filter(u=>(f.city==='all'||u.city===f.city)&&formatMatches(u,f.format||'all')&&(!f.planOnly||isPlanned(u))&&(!q||[u.title,u.city,u.program,u.model,u.formats.join(' ')].join(' ').toLowerCase().includes(q)));
    box.innerHTML=arr.length?arr.map(u=>{const plan=isPlanned(u),checked=state.v10Compare.includes(u.id);return `<div class="uniCard10 ${plan?'inplan':''}"><div class="titleline"><div><h3>${safe(u.title)}</h3><div class="meta">${safe(u.city)} · ${safe(u.program)}</div></div><span class="status ${plan?'g':'y'}">${plan?'в плане':'смотрю'}</span></div><div class="uniTags10"><span>${safe(u.model)}</span><span>${u.portfolio?'портфолио':'без отдельного портфолио в текущей модели'}</span></div><div class="score"><span>Кампания / версия</span><strong style="font-size:12px;text-align:right">${safe(u.cycle)}</strong></div><div class="score"><span>Статус данных</span><strong style="font-size:12px;text-align:right">${safe(u.status)}</strong></div><label class="comparePick"><input type="checkbox" ${checked?'checked':''} onchange="toggleV10Compare('${u.id}')"> Добавить к сравнению</label><div class="uniActions10"><button class="btn secondary" onclick="go('${u.screen}')">Подробнее</button><button class="btn ${plan?'ghost':''}" onclick="toggleV10Plan('${u.id}')">${plan?'Убрать из плана':'Добавить в план'}</button></div></div>`}).join(''):'<div class="empty10">По этим фильтрам пока ничего нет.</div>';setText10('v10CompareCount',state.v10Compare.length)}

  function renderCompare10(){const box=document.getElementById('compare10List');if(!box)return;const selected=state.v10Compare.map(id=>UNIS[id]).filter(Boolean);setText10('compare10Count',selected.length);if(selected.length<2){box.innerHTML='<div class="card yellow"><h3>Нужно минимум два вуза</h3><p>Вернитесь в каталог и отметьте 2–3 программы.</p></div>';return}box.innerHTML=selected.map(u=>`<div class="compareUni10"><div class="row between"><div><h3>${safe(u.title)}</h3><p class="meta">${safe(u.city)}</p></div><span class="status ${isPlanned(u)?'g':'y'}">${isPlanned(u)?'в плане':'не в плане'}</span></div><div class="compareField10"><span>Программа</span><b>${safe(u.program)}</b></div><div class="compareField10"><span>Модель ДВИ</span><b>${safe(u.model)}</b></div><div class="compareField10"><span>Портфолио</span><b>${u.portfolio?'учитывается / требуется в текущей модели':'отдельного требования в базе нет'}</b></div><div class="compareField10"><span>Бюджет</span><b>${safe(u.budget)}</b></div><div class="compareField10"><span>Стоимость</span><b>${safe(u.tuition)}</b></div><div class="compareField10"><span>Данные</span><b>${safe(u.status)}</b></div><button class="btn secondary" onclick="go('${u.screen}')">Открыть ${safe(u.title)}</button></div>`).join('')+`<div class="card softo"><h3>Что сравнивать дальше</h3><p>Когда добавим подтверждённые данные следующих кампаний, сюда автоматически попадут проходной балл прошлого набора, бюджет/платное, стоимость, форма обучения, общежитие и календарь.</p></div>`}

  window.toggleV10Compare=function(id){const a=state.v10Compare;const i=a.indexOf(id);if(i>=0)a.splice(i,1);else{if(a.length>=3){toast('Можно сравнивать максимум 3 программы одновременно');renderCatalog10();return}a.push(id)}saveState();renderV10()};
  window.openV10Compare=function(){if(state.v10Compare.length<2){toast('Выберите минимум два вуза');return}go('uniCompare10')};
  window.toggleV10Plan=function(id){const u=UNIS[id];if(!u)return;state[u.stateKey]=!state[u.stateKey];saveState();toast(state[u.stateKey]?u.title+' добавлен в план':u.title+' убран из плана');renderV10()};

  function bindCatalogFilters(){const q=document.getElementById('v10UniQuery'),c=document.getElementById('v10City'),f=document.getElementById('v10Format'),p=document.getElementById('v10PlanOnly');if(q&&!q.dataset.bound){q.dataset.bound='1';q.value=state.v10Catalog.query||'';q.addEventListener('input',()=>{state.v10Catalog.query=q.value;saveState();renderCatalog10()})}if(c&&!c.dataset.bound){c.dataset.bound='1';c.value=state.v10Catalog.city||'all';c.addEventListener('change',()=>{state.v10Catalog.city=c.value;saveState();renderCatalog10()})}if(f&&!f.dataset.bound){f.dataset.bound='1';f.value=state.v10Catalog.format||'all';f.addEventListener('change',()=>{state.v10Catalog.format=f.value;saveState();renderCatalog10()})}if(p&&!p.dataset.bound){p.dataset.bound='1';p.checked=!!state.v10Catalog.planOnly;p.addEventListener('change',()=>{state.v10Catalog.planOnly=p.checked;saveState();renderCatalog10()})}}

  function dashboardNext(){const plan=plannedUnis();if(!plan.length)return {title:'Выберите хотя бы одну цель поступления',why:'Без выбранного вуза приложение не должно притворяться, что знает ваш персональный маршрут.',go:'uniCatalog',cta:'Выбрать вуз'};const recall=state.mediaRecall||{};if(!String(recall.media||'').trim()||!String(recall.journalists||'').trim())return {title:'Соберите исходную медиакарту',why:'Медиасреда нужна для повестки и собеседований, а первый шаг ещё не сохранён полностью.',go:'agendaHub',cta:'Продолжить медиасреду'};const hasOral=plan.some(u=>u.formats.some(x=>/коллоквиум|собесед/.test(x)));if(hasOral&&!(state.interviewSessions||[]).length)return {title:'Пройдите первую общую симуляцию собеседования',why:'У вас выбран вуз с устным испытанием, но ещё нет ни одной полной тренировочной беседы.',go:'interviewSimulationSetup',cta:'Начать симуляцию'};if((state.newsCount||0)<10)return {title:'Продолжите базу MMT: новости',why:'Базовая практика остаётся общей для разных журфаков и не должна исчезать за вузовской специализацией.',go:'newsCourse',cta:'Продолжить новости'};return {title:'Проверьте слабые места после тренировок',why:'Основные входные шаги уже сделаны. Следующий маршрут лучше строить от накопленных попыток и ошибок.',go:'trialCenter',cta:'Открыть диагностику'};}
  function renderDashboard10(){const box=document.getElementById('v10Dashboard');if(!box)return;const plan=plannedUnis(),next=dashboardNext();const diet=(state.mediaDiet?.media?.length||0)+(state.mediaDiet?.journalists?.length||0);const sims=(state.interviewSessions||[]).length;const works=(state.works||[]).length;const needs=[];if(diet<10)needs.push(['M','Медиарацион',diet+' / 10']);if(plan.some(u=>u.portfolio)&&works<3)needs.push(['P','Портфолио','проверьте комплект']);if(plan.some(u=>u.formats.some(x=>/коллоквиум|собесед/.test(x)))&&sims<2)needs.push(['Q','Собеседование',sims+' симуляций']);const unknownDates=plan.filter(u=>u.id!=='gitr').length; if(unknownDates)needs.push(['D','Даты кампании','нужна актуализация']);box.innerHTML=`<div class="row between"><div><div class="eye">Следующее действие</div><div class="next10">${safe(next.title)}</div></div><span class="status o">по прогрессу</span></div><p class="meta">${safe(next.why)}</p><button class="btn" data-go="${next.go}">${safe(next.cta)}</button><div class="label">Мои цели</div><div class="planChips10">${plan.length?plan.map(u=>`<span>${safe(u.title)}</span>`).join(''):'<span>пока нет</span>'}</div><div class="row between"><b>Требует внимания</b><button class="btn small ghost" data-go="calendar">Календарь</button></div><div class="attention10">${needs.length?needs.slice(0,4).map(n=>`<div class="attentionItem10"><div class="ico">${n[0]}</div><div><b>${safe(n[1])}</b><small>${safe(n[2])}</small></div><span>›</span></div>`).join(''):'<div class="empty10">Критичных незавершённых системных шагов сейчас не найдено.</div>'}</div>`}

  function planDeadlines(){const out=[];plannedUnis().forEach(u=>u.deadlineNotes.filter(d=>!d.archive).forEach(d=>out.push({...d,uni:u.title,uniId:u.id})));return out}
  function archiveDeadlines(){const out=[];plannedUnis().forEach(u=>u.deadlineNotes.filter(d=>d.archive).forEach(d=>out.push({...d,uni:u.title,uniId:u.id})));return out}
  function deadlineCard(d,archive){const done=!!state.v10DeadlineDone[d.id],rem=!!state.v10Reminders[d.id];return `<div class="deadline10 ${done?'done':''} ${archive?'archive10':''}"><div class="dtop"><div><b>${safe(d.label)}</b><div class="meta">${safe(d.uni)}</div></div><span class="status ${archive?'y':done?'g':'o'}">${archive?'архив 2026':done?'готово':'активно'}</span></div><div class="when">${safe(d.when)}</div><p class="meta">${safe(d.action)}</p>${archive?'<div class="source">Не использовать как дату следующей приёмной кампании.</div>':''}<div class="deadlineActions10"><button class="btn small secondary" onclick="toggleDeadlineDone10('${d.id}')">${done?'Вернуть':'Отметить выполненным'}</button>${archive?'':`<button class="btn small ghost" onclick="toggleReminder10('${d.id}')">${rem?'🔔 напоминание включено':'○ напомнить'}</button>`}</div></div>`}
  function renderDeadlines10(){const p=document.getElementById('deadlinePlan10'),a=document.getElementById('archiveDeadlineList10'),c=document.getElementById('customDeadlineList10'),sel=document.getElementById('customDeadlineUni10');if(p){const items=planDeadlines();const plan=plannedUnis();p.innerHTML=`<div class="card"><div class="row between"><div><h3>Обязательные шаги моих вузов</h3><p class="meta">Даты появляются только когда они есть в базе</p></div><span class="status o">${items.length}</span></div>${!plan.length?'<div class="empty10">Сначала добавьте вуз в план.</div>':!items.length?'<div class="empty10">Для выбранных вузов в прототипе пока нет актуальной даты следующей кампании. Мы не переносим даты 2026 автоматически.</div>':items.map(d=>deadlineCard(d,false)).join('')}</div>`}if(a){const items=archiveDeadlines();a.innerHTML=items.length?`<div class="card"><h3>Архив кампании 2026</h3><p class="sub">Полезен для понимания последовательности, но не для планирования следующего поступления.</p>${items.map(d=>deadlineCard(d,true)).join('')}</div>`:''}if(c){c.innerHTML=state.v10CustomDeadlines.length?`<div class="card"><h3>Мои личные даты</h3>${state.v10CustomDeadlines.map((d,i)=>`<div class="deadline10 ${d.done?'done':''}"><div class="dtop"><div><b>${safe(d.title)}</b><div class="meta">${safe(d.uni||'Личное')}</div></div><span class="status ${d.done?'g':'o'}">${d.done?'готово':'моя дата'}</span></div><div class="when">${safe(d.date||'без даты')}</div><div class="deadlineActions10"><button class="btn small secondary" onclick="toggleCustomDeadline10(${i})">${d.done?'Вернуть':'Готово'}</button><button class="btn small ghost" onclick="removeCustomDeadline10(${i})">Удалить</button></div></div>`).join('')}</div>`:''}if(sel){const plan=plannedUnis();sel.innerHTML='<option value="">Личное / без вуза</option>'+plan.map(u=>`<option value="${u.id}">${safe(u.title)}</option>`).join('')}}
  window.toggleDeadlineDone10=function(id){state.v10DeadlineDone[id]=!state.v10DeadlineDone[id];saveState();renderV10()};window.toggleReminder10=function(id){state.v10Reminders[id]=!state.v10Reminders[id];saveState();toast(state.v10Reminders[id]?'Демо-напоминание включено':'Напоминание выключено');renderV10()};
  window.addCustomDeadline10=function(){const title=(document.getElementById('customDeadlineTitle10')?.value||'').trim(),date=document.getElementById('customDeadlineDate10')?.value||'',uid=document.getElementById('customDeadlineUni10')?.value||'';if(!title){toast('Введите, что нужно сделать');return}state.v10CustomDeadlines.push({title,date,uni:uid&&UNIS[uid]?UNIS[uid].title:'',done:false});saveState();const t=document.getElementById('customDeadlineTitle10'),d=document.getElementById('customDeadlineDate10');if(t)t.value='';if(d)d.value='';toast('Личная дата добавлена');renderV10()};
  window.toggleCustomDeadline10=function(i){if(!state.v10CustomDeadlines[i])return;state.v10CustomDeadlines[i].done=!state.v10CustomDeadlines[i].done;saveState();renderV10()};window.removeCustomDeadline10=function(i){state.v10CustomDeadlines.splice(i,1);saveState();renderV10()};

  function setText10(id,v){const x=document.getElementById(id);if(x)x.textContent=v}
  function renderPassports10(){Object.values(UNIS).forEach(u=>{const x=document.getElementById('passPlan-'+u.id);if(x){x.textContent=isPlanned(u)?'в моём плане':'не добавлен';x.className='status '+(isPlanned(u)?'g':'y')}})}
  function renderV10(){injectPassports();bindCatalogFilters();renderCatalog10();renderCompare10();renderDashboard10();renderDeadlines10();renderPassports10()}
  window.renderV10=renderV10;

  const oldRefresh=window.refresh;if(typeof oldRefresh==='function'){window.refresh=function(){oldRefresh();renderV10()}}
  renderV10();
})();
