/* MMT ДВИ v0.13.6 — first real content block: expanded news notes */
(function setupV0136(){
  const main=document.querySelector('main');
  if(!main)return;
  const ver=document.querySelector('.ver');if(ver)ver.textContent='v0.13.6';
  document.title='MMT ДВИ — v0.13.6';

  const safe=s=>typeof esc==='function'?esc(String(s??'')):String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const persist=()=>{try{localStorage.setItem('mmtV04',JSON.stringify(state))}catch(e){console.warn('[MMT v0.13.6] persist failed',e)}};
  state.v136News=state.v136News&&typeof state.v136News==='object'?state.v136News:{lessons:{},micro:{},practice:{}};
  state.v136News.lessons=state.v136News.lessons||{};
  state.v136News.micro=state.v136News.micro||{};
  state.v136News.practice=state.v136News.practice||{};

  const css=document.createElement('style');css.id='mmt-v0136-css';css.textContent=`
    .news136Hero{background:#0c0c0c;color:#fff;border-radius:22px;padding:18px;margin:10px 0}.news136Hero .meta{color:#bbb}.news136Hero h2{font-size:29px;margin:5px 0 7px}.news136Hero p{color:#d6d6d6;font-size:13px;line-height:1.5}.news136Formula{display:flex;gap:5px;flex-wrap:wrap;margin-top:12px}.news136Formula span{font-size:10px;border:1px solid #ffffff28;background:#ffffff12;border-radius:999px;padding:6px 8px}
    .news136Progress{background:var(--os);border-radius:17px;padding:13px;margin:10px 0}.news136ProgressLine{display:flex;justify-content:space-between;gap:8px;padding:5px 0;font-size:12px}.news136List{display:grid;gap:8px;margin:10px 0}.news136Card{background:#fff;border:1px solid var(--line);border-radius:17px;padding:13px;text-align:left;color:var(--ink);width:100%}.news136Card.done{border-color:#a7c7a8}.news136Card b{font-size:14px;display:block}.news136Card small{color:var(--soft);font-size:11px;line-height:1.4;display:block;margin-top:4px}.news136Card .row{align-items:flex-start}.news136Num{width:28px;height:28px;border-radius:9px;background:var(--muted);display:grid;place-items:center;font-size:11px;font-weight:800;flex:0 0 auto}.news136Status{font-size:9px;border-radius:999px;background:var(--muted);padding:5px 7px;white-space:nowrap}.news136Status.ok{background:#e8f3e8}.news136Status.wait{background:var(--os)}
    .news136LessonHead{background:var(--os);border-radius:19px;padding:15px;margin:10px 0}.news136LessonHead h2{font-size:25px;margin:4px 0 7px}.news136Text{background:#fff;border:1px solid var(--line);border-radius:18px;padding:15px;margin:9px 0}.news136Text h3{font-size:18px;margin:0 0 8px}.news136Text p,.news136Text li{font-size:13px;line-height:1.52}.news136Text ul{padding-left:20px}.news136Rule{border-left:4px solid var(--o);padding:9px 12px;background:var(--os);border-radius:0 13px 13px 0;margin:10px 0;font-size:12px;line-height:1.45}.news136Example{background:var(--muted);border-radius:14px;padding:12px;margin:10px 0;font-size:12px;line-height:1.45}.news136Example b{display:block;margin-bottom:4px}.news136Micro{background:#fff;border:2px solid var(--o);border-radius:18px;padding:14px;margin:12px 0}.news136Micro h3{font-size:17px}.news136Option{width:100%;background:#fff;border:1px solid var(--line);border-radius:13px;padding:11px;margin:5px 0;text-align:left;font-size:12px;line-height:1.4;color:var(--ink)}.news136Option.correct{border-color:#6aa46c;background:#eef7ee}.news136Option.wrong{border-color:#c36e6e;background:#faeeee}.news136Feedback{display:none;font-size:12px;line-height:1.45;margin-top:8px;padding:9px 10px;border-radius:12px;background:var(--muted)}.news136Feedback.show{display:block}.news136LessonActions{display:grid;gap:7px;margin:12px 0}.news136LessonActions .btn{margin:0}
    .news136PracticeHero{background:#0c0c0c;color:#fff;border-radius:20px;padding:16px;margin:10px 0}.news136PracticeHero .meta{color:#bbb}.news136PracticeHero h2{font-size:24px;margin:5px 0}.news136PracticeHero p{color:#d0d0d0;font-size:12px;line-height:1.45}.news136Facts{background:#fff;border:1px solid var(--line);border-radius:18px;padding:14px;margin:10px 0}.news136Facts h3{font-size:17px;margin-bottom:8px}.news136Facts li{font-size:12px;line-height:1.45;margin:6px 0}.news136Fiction{background:var(--os);border-radius:12px;padding:9px 10px;font-size:10px;line-height:1.4;margin:8px 0}.news136Field{margin:11px 0}.news136Field label{display:block;font-size:11px;font-weight:700;margin-bottom:5px}.news136Field .input,.news136Field .textarea{width:100%;box-sizing:border-box}.news136Field .textarea{min-height:100px}.news136Field.long .textarea{min-height:150px}.news136Check{background:#fff;border:1px solid var(--line);border-radius:16px;padding:13px;margin:11px 0}.news136Check label{display:flex;gap:8px;align-items:flex-start;font-size:11px;line-height:1.4;margin:8px 0}.news136Check input{margin-top:2px;accent-color:var(--o)}.news136PracticeActions{display:grid;gap:7px;margin:12px 0}.news136PracticeActions .btn{margin:0}.news136Saved{font-size:10px;color:var(--soft);text-align:center;margin-top:6px}
    .route135Module.news136Open{cursor:pointer}.route135Module.news136Open .tag{background:var(--o);color:#0c0c0c}.news136RouteButton{border:0;background:transparent;color:var(--o);font-size:10px;font-weight:800;padding:4px 0;margin-top:5px}
  `;document.head.appendChild(css);

  function ensureScreen(id){let s=document.getElementById(id);if(!s){s=document.createElement('section');s.id=id;s.className='screen';main.appendChild(s)}return s}
  const hub=ensureScreen('newsCourse136');
  const lessonScreen=ensureScreen('newsLesson136');
  const practiceScreen=ensureScreen('newsPractice136');

  const lessons=[
    {
      id:'occasion',title:'Инфоповод и шесть вопросов',time:'7–10 мин',
      intro:'До структуры текста нужно понять, что именно произошло и почему это новость.',
      body:`<h3>Сначала — событие, потом текст</h3><p><b>Информационный повод</b> — новое событие, решение, действие, факт или высказывание, из-за которого материал нужно публиковать именно сейчас.</p><div class="news136Rule"><b>Шесть базовых вопросов:</b> кто? что? где? когда? почему? как?</div><p>Не обязательно механически запихивать все шесть ответов в первый абзац. Но журналист должен знать ответы до того, как начнёт писать расширенную заметку. Если ответа нет — это сигнал, что фактуру ещё нужно собирать.</p><div class="news136Example"><b>Не инфоповод:</b> «В библиотеке много книг».<br><b>Инфоповод:</b> «С сентября библиотека впервые будет работать до полуночи по пятницам».</div>`,
      q:'Что здесь сильнее всего похоже на инфоповод?',options:['В университете есть медиакласс.','С понедельника медиакласс впервые станет круглосуточным для студентов журфака.','Студенты часто работают над проектами вечером.'],correct:1,feedback:'Да. Есть новое действие и понятный момент, когда оно начинается — из этого уже можно строить новость.'
    },
    {
      id:'structure',title:'Структура расширенной новостной заметки',time:'8–12 мин',
      intro:'Фиксируем каркас, который дальше будет повторяться во всех десяти работах.',
      body:`<h3>Рабочая конструкция MMT</h3><div class="news136Rule"><b>Заголовок-шило → лид → тело → комментарий → бэкграунд.</b></div><p><b>Ядро</b> сообщает суть и значение события. Оно всегда находится в начале. <b>Детали</b> раскрывают сюжет, позиции сторон, яркие подробности, оценки и прогнозы. <b>Бэкграунд</b> объясняет предысторию и контекст.</p><p>Полезный ориентир по объёму: ядро — около 10%, детали — 50–70%, бэкграунд — 20–40%. Это не математическая формула, но хороший редакторский тест: если половина текста — старая история, скорее всего, нового события вы собрали недостаточно.</p>`,
      q:'Что должно занимать основную часть расширенной заметки?',options:['Бэкграунд — чем больше истории, тем солиднее текст.','Детали нового события: сюжет, позиции, подробности, оценки.','Заголовок и лид.'],correct:1,feedback:'Верно. Основной объём — новая фактура и детали события; бэкграунд помогает понять их, но не подменяет репортёрскую работу.'
    },
    {
      id:'headline',title:'Заголовок-шило',time:'6–9 мин',
      intro:'Заголовок должен сразу проткнуть событие: коротко, точно и по главному факту.',
      body:`<h3>Не украшение, а главный факт</h3><p>В нашей подготовке используем <b>заголовок-шило</b>: короткий, прямой, без тумана. Он соответствует смыслу заметки и сразу выносит вперёд главное изменение.</p><p>Не надо придумывать игру слов только ради игры слов. Читатель должен понять новость ещё до лида.</p><div class="news136Example"><b>Слабее:</b> «Книги не спят»<br><b>Шило:</b> «Городская библиотека продлит работу до полуночи по пятницам»</div><p>Если в событии есть сильная цифра, решение, запрет, запуск, отмена или изменение — часто именно оно и становится остриём заголовка.</p>`,
      q:'Какой заголовок ближе к принципу «шила»?',options:['Ночная жизнь знаний','Медиакласс университета станет круглосуточным','Студентов ждут большие перемены'],correct:1,feedback:'Да. Сразу понятен главный факт, нет необходимости расшифровывать метафору.'
    },
    {
      id:'leadbody',title:'Лид и тело новости',time:'10–14 мин',
      intro:'Лид сообщает главное, тело доказывает, раскрывает и развивает его.',
      body:`<h3>Лид: сильное начало</h3><p>Лид — первый абзац расширенной заметки. Он раскрывает заголовок и даёт читателю ключевую фактуру: кто/что, где, когда, а при необходимости — сколько, почему и чем это важно.</p><div class="news136Rule">Источник информации должен появляться рано — обычно не дальше второго абзаца. Сначала сообщаем новость, затем объясняем, откуда она известна.</div><h3>Тело: новое событие подробно</h3><p>Здесь появляются хронология, механизм решения, участники, цифры, позиции сторон, последствия и яркие детали. Связки между абзацами должны быть логическими: каждый следующий абзац отвечает на естественный вопрос, который возник после предыдущего.</p>`,
      q:'Какой лид сильнее?',options:['Вчера стало известно о том, что в городе происходят изменения в работе транспорта.','С 1 сентября ночной автобус №N будет ходить между вокзалом и студенческим кварталом каждый час, сообщил городской транспортный центр.','Транспорт — важная часть жизни любого большого города.'],correct:1,feedback:'Верно. В первом абзаце уже есть изменение, дата, маршрут и источник — читатель понимает, что произошло.'
    },
    {
      id:'comment',title:'Комментарий: не декоративная цитата',time:'10–15 мин',
      intro:'Комментарий нужен, чтобы получить позицию, объяснение, последствия или прогноз.',
      body:`<h3>Кого спрашивать?</h3><ul><li><b>Участника события</b> — что произошло с его стороны, чего он хочет, что будет делать.</li><li><b>Вторую сторону</b> — если есть спор, претензия или решение, которое кого-то затрагивает.</li><li><b>Эксперта</b> — почему событие важно, к чему может привести, насколько решение типично или эффективно.</li></ul><p>Комментарий не должен существовать только ради кавычек. До звонка сформулируйте, <b>какой пробел в тексте должен закрыть этот человек</b>.</p><div class="news136Rule">Слабый вопрос: «Что вы думаете?»<br>Сильнее: «Как это решение изменит работу студентов после 22:00 и какие риски вы видите?»</div>`,
      q:'Университет повышает стоимость общежития. Кого важнее всего добавить кроме администрации?',options:['Случайного прохожего у корпуса.','Студента, который живёт в общежитии, и при необходимости независимого эксперта по студенческой социальной политике.','Любого преподавателя, даже если он не связан с темой.'],correct:1,feedback:'Да. Комментарий должен быть связан с последствиями новости и закрывать конкретный вопрос.'
    },
    {
      id:'background',title:'Бэкграунд: предыстория, которая работает',time:'8–12 мин',
      intro:'Бэкграунд отвечает не «что ещё я нашёл в интернете», а «что читателю нужно знать, чтобы понять новое событие».',
      body:`<h3>Три полезных вида</h3><ul><li><b>Статистический:</b> сколько подобных событий уже было, как менялись показатели.</li><li><b>Исторический:</b> что раньше происходило с участниками или самим проектом.</li><li><b>Контекстуальный:</b> какое соседнее событие меняет смысл нынешней новости.</li></ul><p>Бэкграунд можно размещать не только в самом конце, но ядро всегда должно оставаться впереди. Если старая история заняла половину материала, проверьте: возможно, вы недособрали детали нового события.</p>`,
      q:'Какой фрагмент — исторический бэкграунд?',options:['За прошлый год ночным маршрутом воспользовались 240 тысяч пассажиров.','Предыдущую попытку запустить ночной маршрут город отменил в 2023 году после трёх месяцев работы.','На этой неделе вокзал также изменил схему входа.'],correct:1,feedback:'Верно. Это предыстория именно этого решения и его прошлой попытки.'
    },
    {
      id:'assembly',title:'Собираем заметку целиком',time:'10–15 мин',
      intro:'Перед практикой превращаем структуру в редакторский чек-лист.',
      body:`<h3>Перед публикацией проверьте семь вещей</h3><ul><li><b>Шило:</b> в заголовке главный факт, а не атмосфера.</li><li><b>Лид:</b> новость понятна человеку, который прочитает только первый абзац.</li><li><b>Тело:</b> достаточно новой фактуры — как, почему, кто участвует, что изменится.</li><li><b>Источник:</b> ясно, откуда взяты ключевые сведения.</li><li><b>Комментарий:</b> цитата или позиция добавляет информацию, а не повторяет лид.</li><li><b>Бэкграунд:</b> помогает понять событие и не перетягивает текст на прошлое.</li><li><b>Что дальше:</b> если развитие известно, читатель не остаётся в пустоте.</li></ul><div class="news136Rule">Практика дальше всегда полная: заголовок-шило + лид + тело + комментарий + бэкграунд. Мы не будем засчитывать «пол-новости» как готовую работу.</div>`,
      q:'В тексте есть сильный лид, подробное тело и длинная история проекта, но нет ни одной позиции человека. Что прежде всего нужно добрать?',options:['Ещё один абзац бэкграунда.','Комментарий участника, второй стороны или эксперта — в зависимости от пробела в тексте.','Более красивый заголовок.'],correct:1,feedback:'Точно. Хорошая расширенная заметка должна быть собрана репортёром, а не только из старых публикаций.'
    }
  ];

  const practices=[
    {id:1,title:'Библиотека до полуночи',focus:'Базовая расширенная заметка · один главный источник + пользователь',facts:[
      'Учебный город N. Центральная библиотека с 5 сентября будет работать по пятницам до 00:00 вместо 20:00.','Режим вводят как трёхмесячный пилот. Остальные дни библиотека закрывается по прежнему расписанию.','Директор библиотеки Анна Миронова: «Мы видим, что после 18:00 читальные залы заняты почти полностью, особенно в сессию. Если пилот будет востребован, обсудим постоянный режим».','По данным библиотеки, в мае опрос прошли 820 посетителей, 63% из них просили продлить вечерние часы.','Студент второго курса Илья Савин: «После пар я успеваю сюда только к семи. Дополнительные часы реально дадут возможность готовиться здесь, а не искать кафе».','Два года назад библиотека уже продлевала работу до 22:00 на две недели во время зимней сессии.' ]},
    {id:2,title:'Круглосуточный медиакласс',focus:'Цифры, условия доступа и последствия',facts:[
      'Университет N с 1 октября откроет круглосуточный доступ в медиакласс корпуса журналистики.','Сейчас класс работает с 09:00 до 21:00. В нём 24 монтажных компьютера и две кабины звукозаписи.','Проректор Мария Ветрова: «Ночной доступ получат студенты после регистрации проекта и бронирования рабочего места. Просто находиться в аудитории ночью будет нельзя».','Студсовет просил расширить часы после опроса 410 студентов: 58% сообщили, что хотя бы раз не успевали закончить монтаж до закрытия корпуса.','Председатель студсовета Роман Лебедев считает главным риском нехватку дежурных технических специалистов ночью.','Университет планирует первые два месяца держать ночного администратора только с четверга по воскресенье, затем оценить нагрузку.' ]},
    {id:3,title:'Фестиваль переезжает из парка',focus:'Изменение площадки + комментарий организатора и участника',facts:[
      'Молодёжный фестиваль «Город говорит» перенесли из Центрального парка в выставочный центр за четыре дня до открытия.','Организаторы объяснили перенос прогнозом сильного ветра и запретом устанавливать временные сцены в парке при порывах выше 15 м/с.','Все билеты действительны, даты и время программы не меняются. Вместимость новой площадки меньше на 600 человек.','Продюсер фестиваля Артём Беляев: «Мы убрали дополнительную продажу билетов и сохранили уже заявленные выступления».','Участница дискуссионной программы Лиза Орлова говорит, что организаторы предупредили её команду вечером накануне публичного объявления.','Фестиваль проходит пятый год; два предыдущих года он проводился в Центральном парке.' ]},
    {id:4,title:'Новая система пропусков',focus:'Две стороны и конфликт интересов',facts:[
      'Колледж N с 15 сентября вводит электронные пропуска через мобильное приложение; пластиковые карты перестанут работать 1 октября.','Администрация объясняет решение необходимостью быстрее блокировать потерянные пропуска и видеть загрузку корпусов.','Для входа приложению нужен динамический QR-код, обновляющийся каждые 30 секунд.','Студенты без подходящего смартфона смогут получить отдельную карту после заявления.','Председатель студсовета Дарья Лукина: «Нас беспокоит, какие именно данные будут храниться и как долго. Мы запросили положение об обработке информации».','Замдиректора колледжа Сергей Мельников: «Геолокацию приложение не собирает. В системе фиксируется только факт прохода через турникет».','Сейчас в колледже учатся 3,8 тысячи человек; пластиковая система пропусков работает с 2017 года.' ]},
    {id:5,title:'Бассейн закрывают на ремонт',focus:'Сроки, пользователи, деньги и бэкграунд',facts:[
      'Спортивный центр N закроет единственный 25-метровый бассейн на ремонт с 10 июня по 25 августа.','Стоимость работ — 18 млн условных рублей; подрядчик заменит систему фильтрации и часть облицовки чаши.','Абонементы заморозят автоматически. Спортивные группы временно переведут в бассейн соседнего района по отдельному расписанию.','Директор центра Павел Громов: «Последний капитальный ремонт был девять лет назад. Зимой мы дважды останавливали одну из линий фильтрации из-за неисправностей».','Тренер детской секции Оксана Грина опасается, что дорога до временной площадки увеличит путь для части семей на 35–40 минут.','В центре занимаются 11 детских групп и около 1,4 тысячи владельцев абонементов.' ]},
    {id:6,title:'Ночной автобус',focus:'Экспертный комментарий и прогноз',facts:[
      'Город N запускает с 20 сентября ночной автобус N7 между железнодорожным вокзалом и студенческим кварталом.','Автобус будет ходить с 00:30 до 05:30 раз в час по пятницам и субботам. Обычный городской тариф сохраняется.','Транспортный центр рассчитывает перевозить около 450 пассажиров за ночь.','Руководитель центра Алексей Нестеров: «Если средняя загрузка будет ниже 15 пассажиров на рейс в течение трёх месяцев, расписание пересмотрим».','Независимый транспортный аналитик Вера Климова считает часовым интервал слишком большим для устойчивого спроса и предлагает оценивать не только число пассажиров, но и пересадки с ночных поездов.','В 2023 году город уже тестировал ночной маршрут по другой трассе; его закрыли через три месяца из-за средней загрузки 8 пассажиров на рейс.' ]},
    {id:7,title:'Редакция меняет ритм выпуска',focus:'Решение + мотив + реакция аудитории',facts:[
      'Студенческое издание «Кампус» с октября переходит с ежедневных коротких выпусков на один большой еженедельный номер и оперативный Telegram-канал.','Главный редактор объясняет решение тем, что команда из 14 человек тратила большую часть времени на переписывание пресс-релизов и редко выпускала собственные материалы.','За прошлый семестр издание опубликовало 312 заметок, из них 46 были оригинальными материалами с собственными комментариями.','Главред Егор Платонов: «Мы не отказываемся от новостей. Срочные вещи останутся в канале, а сайт должен давать то, чего нет в официальных сообщениях».','Читательница и студентка Полина Рудакова говорит, что использовала сайт прежде всего как календарь университетских событий и боится потерять эту функцию.','Издание работает при университете с 2019 года; нынешняя модель ежедневной ленты появилась в 2022-м.' ]},
    {id:8,title:'Часть программы отменили',focus:'Неполная информация, ответственность и вторая сторона',facts:[
      'Организаторы городского кинофорума N отменили три уличных показа за два дня до начала мероприятия.','Причина — подрядчик не успел поставить сертифицированные экраны и звуковое оборудование. Остальная программа форума сохраняется.','Зрителям, купившим отдельные билеты на отменённые показы, обещают автоматический возврат в течение десяти рабочих дней.','Директор форума Нина Соколова: «Мы получили от подрядчика подтверждение готовности ещё неделю назад. В четверг выяснилось, что часть оборудования не прошла проверку».','Представитель подрядчика Игорь Дёмин утверждает, что организаторы поздно изменили технические требования к двум площадкам и не согласовали дополнительную смету.','Контракт на оборудование оценивался в 4,2 млн условных рублей. В прошлом году уличные показы форума посетили около 7 тысяч человек.' ]},
    {id:9,title:'Общежитие дорожает',focus:'Социальное решение, цифры и несколько позиций',facts:[
      'Университет N с января повышает плату за общежитие в среднем на 18%.','Для стандартной комнаты плата вырастет с 2 400 до 2 830 условных рублей в месяц; коммунальные услуги входят в сумму.','Администрация ссылается на рост расходов на охрану, уборку и текущий ремонт.','Проректор по хозяйственной работе Олег Вишневский: «Повышение не покрывает все дополнительные расходы, часть по-прежнему субсидирует университет».','Председатель совета общежитий Милана Гурова говорит, что студентов уведомили за четыре месяца, но совет просит ввести адресную скидку для малообеспеченных.','В четырёх общежитиях университета живут 5,1 тысячи студентов. Последний раз базовую плату меняли два года назад — тогда рост составил 7%.','Университет обещает опубликовать правила получения материальной помощи до 1 ноября.' ]},
    {id:10,title:'Молодёжный медиацентр',focus:'Финальная редакционная работа · несколько источников и много фактуры',facts:[
      'В городе N 1 декабря откроется муниципальный молодёжный медиацентр для школьников и студентов 14–22 лет.','Центр займёт два этажа бывшей районной библиотеки: студию подкастов, видеопавильон, монтажный класс на 18 мест и открытую редакцию.','На ремонт и оборудование выделили 36 млн условных рублей. Обучение обещают сделать бесплатным после конкурсного отбора.','Глава городского молодёжного комитета Ирина Лазарева: «В первый год рассчитываем принять 300 участников в длинные программы и около двух тысяч человек на открытые события».','Руководить учебной частью пригласили бывшего редактора регионального телеканала Максима Арсеньева. Он говорит, что минимум половина занятий будет строиться на реальных городских заданиях, а лучшие работы планируют отдавать партнёрским редакциям.','Редактор независимого городского издания Светлана Коваль считает, что центру нужно публично объяснить правила редакционной независимости: «Если материалы о городских проблемах будут проходить согласование у чиновников, это станет кружком пресс-службы, а не журналистики».','Комитет отвечает, что предварительное согласование публикаций с администрацией не планируется, но правила работы с несовершеннолетними и съёмками ещё разрабатываются.','Раньше в городе существовала небольшая молодёжная телестудия на 40 мест; её закрыли четыре года назад после переезда Дома молодёжи.','Регистрация на отбор должна открыться 15 октября, критерии конкурса обещают опубликовать за неделю до старта.' ]}
  ];

  function lessonDoneCount(){return lessons.filter(l=>state.v136News.lessons[l.id]).length}
  function practiceDoneCount(){return practices.filter(p=>state.v136News.practice[p.id]?.submitted).length}
  function courseStatus(){const l=lessonDoneCount(),p=practiceDoneCount();if(l===lessons.length&&p===practices.length)return'база освоена';if(l||p)return'в работе';return'не начато'}

  function renderHub(){
    const ld=lessonDoneCount(),pd=practiceDoneCount();
    hub.innerHTML=`<div class="eye">База MMT · практика</div><div class="news136Hero"><div class="meta">Первый содержательный блок</div><h2>Новости</h2><p>Учимся писать не «любой новостной текст», а полноценную расширенную новостную заметку. Все десять практических работ собираются по одной профессиональной конструкции.</p><div class="news136Formula"><span>заголовок-шило</span><span>лид</span><span>тело</span><span>комментарий</span><span>бэкграунд</span></div></div><div class="news136Progress"><div class="news136ProgressLine"><span>Статус</span><b>${courseStatus()}</b></div><div class="news136ProgressLine"><span>Короткие уроки</span><b>${ld}/${lessons.length}</b></div><div class="news136ProgressLine"><span>Расширенные заметки</span><b>${pd}/${practices.length}</b></div></div><h3>Короткая теория</h3><p class="meta">Каждый урок заканчивается одним микрозаданием. Длинных лекций здесь нет.</p><div class="news136List">${lessons.map((l,i)=>`<button type="button" class="news136Card ${state.v136News.lessons[l.id]?'done':''}" data-v136-lesson="${l.id}"><div class="row between"><div style="display:flex;gap:9px;align-items:flex-start"><span class="news136Num">${i+1}</span><div><b>${safe(l.title)}</b><small>${safe(l.intro)} · ${safe(l.time)}</small></div></div><span class="news136Status ${state.v136News.lessons[l.id]?'ok':''}">${state.v136News.lessons[l.id]?'пройден':'открыть'}</span></div></button>`).join('')}</div><h3 style="margin-top:20px">Практика: 10 расширенных новостей</h3><p class="meta">Все кейсы учебные и вымышленные. Фактура дана как редакционный пакет: ваша задача — отобрать главное, выстроить текст и не потерять позиции людей.</p><div class="news136List">${practices.map(p=>{const d=state.v136News.practice[p.id]||{};return`<button type="button" class="news136Card ${d.submitted?'done':''}" data-v136-practice="${p.id}"><div class="row between"><div style="display:flex;gap:9px;align-items:flex-start"><span class="news136Num">${p.id}</span><div><b>${safe(p.title)}</b><small>${safe(p.focus)}</small></div></div><span class="news136Status ${d.submitted?'ok':d.title||d.lead||d.body?'wait':''}">${d.submitted?'к разбору':(d.title||d.lead||d.body)?'черновик':'начать'}</span></div></button>`}).join('')}</div><button class="btn secondary" type="button" data-v136-route>← Вернуться в мой маршрут</button>`;
  }

  function openLesson(id){
    const l=lessons.find(x=>x.id===id);if(!l)return;
    const micro=state.v136News.micro[id];
    lessonScreen.dataset.lesson=id;
    lessonScreen.innerHTML=`<div class="eye">Новости · урок ${lessons.indexOf(l)+1}/${lessons.length}</div><div class="news136LessonHead"><h2>${safe(l.title)}</h2><p class="meta">${safe(l.intro)} · ${safe(l.time)}</p></div><div class="news136Text">${l.body}</div><div class="news136Micro"><div class="eye">Микрозадание</div><h3>${safe(l.q)}</h3>${l.options.map((o,i)=>`<button type="button" class="news136Option ${micro?.choice===i?(micro.correct?'correct':'wrong'):''}" data-v136-micro="${i}">${safe(o)}</button>`).join('')}<div id="news136Feedback" class="news136Feedback ${micro?'show':''}">${micro?(micro.correct?safe(l.feedback):'Пока нет. Посмотрите ещё раз на правило выше и попробуйте другой вариант.'):'Выберите один вариант.'}</div></div><div class="news136LessonActions"><button class="btn" type="button" data-v136-complete-lesson ${micro?.correct?'':'disabled'}>${state.v136News.lessons[id]?'Урок пройден ✓':'Отметить урок пройденным'}</button><button class="btn secondary" type="button" data-v136-hub>К списку уроков</button></div>`;
    if(typeof window.go==='function')window.go('newsLesson136');
  }

  function practiceData(id){return state.v136News.practice[id]=state.v136News.practice[id]||{title:'',lead:'',body:'',comment:'',background:'',checks:{},submitted:false,updatedAt:''}}
  function renderPractice(id){
    const p=practices.find(x=>x.id===Number(id));if(!p)return;
    const d=practiceData(p.id);practiceScreen.dataset.practice=String(p.id);
    const checkItems=[['main','В заголовке-шиле стоит главный факт, а не метафора.'],['lead','Лид позволяет понять новость без чтения остального текста.'],['details','В теле есть новая фактура: как, почему, кто участвует и что изменится.'],['comment','Комментарий добавляет позицию/объяснение/прогноз, а не повторяет уже сказанное.'],['bg','Бэкграунд помогает понять событие и не занимает половину заметки.']];
    practiceScreen.innerHTML=`<div class="eye">Новости · практика ${p.id}/10</div><div class="news136PracticeHero"><div class="meta">${safe(p.focus)}</div><h2>${safe(p.title)}</h2><p>Напишите полноценную расширенную новостную заметку. Фактуру можно сокращать и переставлять, но нельзя добавлять новые факты, которых нет в редакционном пакете.</p></div><div class="news136Fiction"><b>Учебный кейс.</b> Все организации, имена, цифры и события ниже вымышлены специально для тренировки и не описывают реальные события.</div><div class="news136Facts"><h3>Редакционный пакет</h3><ul>${p.facts.map(f=>`<li>${safe(f)}</li>`).join('')}</ul></div><div class="news136Field"><label>Заголовок-шило</label><input class="input" id="news136Title" value="${safe(d.title)}" placeholder="Главный факт одним точным заголовком"></div><div class="news136Field"><label>Лид</label><textarea class="textarea" id="news136Lead" placeholder="Первый абзац: что произошло и почему это важно">${safe(d.lead)}</textarea></div><div class="news136Field long"><label>Основная часть / тело</label><textarea class="textarea" id="news136Body" placeholder="Подробности нового события, механизм, цифры, позиции, последствия">${safe(d.body)}</textarea></div><div class="news136Field"><label>Комментарий</label><textarea class="textarea" id="news136Comment" placeholder="Встройте в заметку нужный комментарий и объясните его роль">${safe(d.comment)}</textarea></div><div class="news136Field"><label>Бэкграунд</label><textarea class="textarea" id="news136Background" placeholder="Предыстория или контекст, который помогает понять событие">${safe(d.background)}</textarea></div><div class="news136Check"><h3>Самопроверка перед разбором</h3>${checkItems.map(([k,t])=>`<label><input type="checkbox" data-v136-check="${k}" ${d.checks?.[k]?'checked':''}> <span>${safe(t)}</span></label>`).join('')}</div><div class="news136PracticeActions"><button class="btn secondary" type="button" data-v136-save-draft>Сохранить черновик</button><button class="btn" type="button" data-v136-submit>${d.submitted?'Работа готова к разбору ✓':'Отправить в список на разбор'}</button><button class="btn secondary" type="button" data-v136-hub>К списку практики</button></div><div class="news136Saved">${d.updatedAt?'Последнее сохранение: '+new Date(d.updatedAt).toLocaleString('ru-RU'):''}</div>`;
    if(typeof window.go==='function')window.go('newsPractice136');
  }

  function collectPractice(){
    const id=Number(practiceScreen.dataset.practice||0);if(!id)return null;
    const d=practiceData(id);
    d.title=document.getElementById('news136Title')?.value.trim()||'';
    d.lead=document.getElementById('news136Lead')?.value.trim()||'';
    d.body=document.getElementById('news136Body')?.value.trim()||'';
    d.comment=document.getElementById('news136Comment')?.value.trim()||'';
    d.background=document.getElementById('news136Background')?.value.trim()||'';
    d.checks=d.checks||{};practiceScreen.querySelectorAll('[data-v136-check]').forEach(c=>d.checks[c.dataset.v136Check]=c.checked);
    d.updatedAt=new Date().toISOString();persist();return d;
  }

  function patchRoute(){
    const r=document.getElementById('myRoute');if(!r)return;
    [...r.querySelectorAll('.route135Module')].forEach(card=>{
      const title=card.querySelector('b')?.textContent?.trim();
      if(title!=='Новости')return;
      card.classList.add('news136Open');card.dataset.v136OpenNews='1';
      const tag=card.querySelector('.tag');if(tag)tag.textContent=`${practiceDoneCount()}/10`;
      if(!card.querySelector('.news136RouteButton')){const b=document.createElement('button');b.type='button';b.className='news136RouteButton';b.textContent='Открыть учебный блок →';card.querySelector('div:nth-child(2)')?.appendChild(b)}
    });
  }
  const route=document.getElementById('myRoute');if(route)new MutationObserver(()=>requestAnimationFrame(patchRoute)).observe(route,{childList:true});

  document.addEventListener('click',e=>{
    const open=e.target.closest('[data-v136-open-news]');if(open){e.preventDefault();renderHub();if(typeof window.go==='function')window.go('newsCourse136');return}
    const l=e.target.closest('[data-v136-lesson]');if(l){e.preventDefault();openLesson(l.dataset.v136Lesson);return}
    const p=e.target.closest('[data-v136-practice]');if(p){e.preventDefault();renderPractice(Number(p.dataset.v136Practice));return}
    if(e.target.closest('[data-v136-hub]')){e.preventDefault();renderHub();if(typeof window.go==='function')window.go('newsCourse136');return}
    if(e.target.closest('[data-v136-route]')){e.preventDefault();if(window.MMT_ROUTE_ENGINE?.sync)window.MMT_ROUTE_ENGINE.sync('news-course');if(typeof window.go==='function')window.go('myRoute');setTimeout(patchRoute,0);return}
    const mo=e.target.closest('[data-v136-micro]');if(mo){e.preventDefault();const id=lessonScreen.dataset.lesson,lx=lessons.find(x=>x.id===id),choice=Number(mo.dataset.v136Micro);if(!lx)return;state.v136News.micro[id]={choice,correct:choice===lx.correct};persist();openLesson(id);return}
    if(e.target.closest('[data-v136-complete-lesson]')){e.preventDefault();const id=lessonScreen.dataset.lesson;if(!state.v136News.micro[id]?.correct)return;state.v136News.lessons[id]=true;persist();renderHub();if(typeof window.go==='function')window.go('newsCourse136');patchRoute();return}
    if(e.target.closest('[data-v136-save-draft]')){e.preventDefault();collectPractice();if(typeof toast==='function')toast('Черновик сохранён');renderPractice(Number(practiceScreen.dataset.practice));return}
    if(e.target.closest('[data-v136-submit]')){e.preventDefault();const d=collectPractice();if(!d)return;const missing=[d.title,d.lead,d.body,d.comment,d.background].filter(x=>!x).length;if(missing){if(typeof toast==='function')toast('Заполните все пять частей расширенной заметки');return}const allChecks=Object.values(d.checks||{}).filter(Boolean).length>=5;if(!allChecks){if(typeof toast==='function')toast('Сначала пройдите самопроверку');return}d.submitted=true;d.updatedAt=new Date().toISOString();persist();renderPractice(Number(practiceScreen.dataset.practice));patchRoute();if(typeof toast==='function')toast('Работа сохранена для разбора');return}
  },true);

  renderHub();patchRoute();
  window.MMT_NEWS_COURSE={render:renderHub,open:()=>{renderHub();if(typeof window.go==='function')window.go('newsCourse136')},state:()=>state.v136News};
})();
