/* MMT ДВИ v0.16.2 — interview module grounded in MMT teaching materials */
(function setupV0162(){
  if(typeof state==='undefined')return;
  const main=document.querySelector('main');if(!main)return;
  const VER='v0.16.2';const ver=document.querySelector('.ver');if(ver)ver.textContent=VER;document.title='MMT ДВИ — '+VER;
  state.v160Interview=state.v160Interview&&typeof state.v160Interview==='object'?state.v160Interview:{};
  const I=state.v160Interview;I.prep=I.prep||{};I.questions=I.questions||{};I.talk=I.talk||{};I.draft=I.draft||{};I.v162=I.v162||{};I.media=I.media||{};
  const safe=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const persist=()=>{try{localStorage.setItem('mmtV04',JSON.stringify(state))}catch(e){console.warn('[MMT v0.16.2]',e)}};
  const notify=m=>{if(typeof toast==='function')toast(m)};const go=id=>{if(typeof window.go==='function')window.go(id)};

  const css=document.createElement('style');css.id='mmt-v0162-css';css.textContent=`
    .int162Box{background:#fff;border:1px solid var(--line);border-radius:18px;padding:14px;margin:10px 0}.int162Box h3{font-size:18px;margin:0 0 8px}.int162Box p,.int162Box li{font-size:12px;line-height:1.5}.int162Box ul,.int162Box ol{padding-left:20px}
    .int162Cards{display:grid;gap:8px}.int162Card{width:100%;text-align:left;background:#fff;border:1px solid var(--line);border-radius:15px;padding:12px;color:var(--ink)}.int162Card b{display:block;font-size:13px}.int162Card small{display:block;color:var(--soft);font-size:10px;line-height:1.4;margin-top:4px}.int162Card.done{border-color:#9cbe9d}
    .int162Rule{border-left:4px solid var(--o);background:var(--os);border-radius:0 13px 13px 0;padding:9px 11px;margin:10px 0;font-size:11px;line-height:1.45}.int162Warn{background:#fff3ea;border:1px solid #eab896;border-radius:13px;padding:10px 11px;font-size:11px;line-height:1.45;margin:9px 0}.int162Tip{background:#eef5ee;border:1px solid #b5cbb5;border-radius:13px;padding:10px 11px;font-size:11px;line-height:1.45;margin:9px 0}
    .int162Choices{display:flex;gap:6px;flex-wrap:wrap;margin:7px 0}.int162Choice{border:1px solid var(--line);background:#fff;border-radius:11px;padding:8px 9px;font-size:10px;font-weight:800;color:var(--ink)}.int162Choice.active{border-color:var(--o);background:var(--os)}.int162Hint{font-size:10px;color:var(--soft);line-height:1.42;margin-top:5px}
    .int162LessonHero{background:#0c0c0c;color:#fff;border-radius:20px;padding:16px;margin:10px 0}.int162LessonHero .meta{color:#bbb}.int162LessonHero h2{font-size:25px;margin:5px 0}.int162LessonHero p{font-size:12px;line-height:1.45;color:#d0d0d0}.int162Option{width:100%;background:#fff;border:1px solid var(--line);border-radius:12px;padding:10px;margin:5px 0;text-align:left;font-size:11px;color:var(--ink)}.int162Option.correct{background:#eef7ee;border-color:#6aa46c}.int162Option.wrong{background:#faeeee;border-color:#c36e6e}
    .int162Upload{display:block;border:1px dashed #bbb;border-radius:13px;padding:12px;text-align:center;font-size:11px;font-weight:800;cursor:pointer;margin:8px 0}.int162Upload input{display:none}.int162Photo img{width:100%;max-height:210px;object-fit:cover;border-radius:11px}.int162Photo .input{width:100%;box-sizing:border-box}.int162Delete{border:0;background:transparent;color:#8e3e3e;font-size:10px;font-weight:800;padding:7px 0}.int162Submit{border-radius:13px;padding:10px 11px;margin:9px 0;font-size:11px;line-height:1.45}.int162Submit.bad{background:#faeeee;border:1px solid #d99a9a}.int162Submit.warn{background:#fff3ea;border:1px solid #eab896}
  `;document.head.appendChild(css);

  let lesson=document.getElementById('interviewLesson162');if(!lesson){lesson=document.createElement('section');lesson.id='interviewLesson162';lesson.className='screen';main.appendChild(lesson)}
  const lessons={
    strategy:{title:'Вид интервью, тип гостя и формат',intro:'Сначала определяем задачу разговора и только потом пишем вопросы.',body:`<h3>Виды интервью</h3><ul><li><b>Информационное</b> — факты и объяснения по событию.</li><li><b>Оперативное</b> — одинаковые вопросы нескольким людям по свежему событию; обычно часть другого материала.</li><li><b>Интервью-расследование</b> — разбор события, решения, конфликта или ответственности.</li><li><b>Интервью-портрет</b> — человек, его опыт, решения, характер и важный этап жизни.</li></ul><h3>Тип собеседника</h3><ul><li><b>Эксперт:</b> переводим профессиональный язык на понятный.</li><li><b>Медийный человек:</b> стараемся выйти за пределы сценического образа к личному опыту.</li><li><b>Чиновник:</b> не даём разговору превратиться в отчёт; спрашиваем о результате, ответственности и том, что не сделано.</li><li><b>Политик:</b> особенно важны конкретика и возвращение к вопросу.</li><li><b>Герой события:</b> говорим проще и помогаем восстановить конкретные сцены.</li></ul><h3>Формат</h3><p>Личная встреча даёт невербальное общение и среду. Синхронное дистанционное интервью позволяет уточнять сразу. Асинхронный список вопросов удобен, но ответы чаще становятся более «причёсанными».</p><div class="int162Rule">При договорённости человек должен понимать, что это интервью для публикации. Если разговор строится вокруг конкретного эпизода или конфликта, тему лучше обозначить заранее.</div>`,q:'Вы хотите раскрыть профессиональный путь человека, его страхи и решения. Что ближе?',opts:['Оперативное интервью','Интервью-портрет','Опрос'],correct:1},
    questions:{title:'Вопросы, управление разговором и уловки',intro:'Хороший список вопросов — маршрут, а не анкета, которую читают сверху вниз.',body:`<h3>Как строить вопросы</h3><ul><li>открытые вопросы обычно предпочтительнее закрытых;</li><li>закрытый вопрос полезен для ясного ответа или после уклонения;</li><li>непрямой вопрос может мягче вводить чувствительную тему;</li><li>один вопрос — одна мысль;</li><li>не вкладывайте в вопрос собственное предположение или желаемый ответ;</li><li>не спорьте вместо того, чтобы спрашивать;</li><li>просите пример, сцену, цифру, источник или доказательство;</li><li>стройте следующий вопрос из ответа собеседника.</li></ul><p>Управляющие вопросы помогают <b>открыть тему</b>, <b>перейти</b> к следующему блоку и <b>отфильтровать уход</b>, возвращая собеседника к предмету разговора.</p><div class="int162Tip"><b>Из реальных ученических работ:</b> длинное интервью хорошо держится на крупных блоках. В одном материале разговор шёл от пути в танце к преподаванию, страхам и будущему; в другом заранее были обозначены три линии — культура страны, преподавание и жизнь за границей.</div><h3>12 типичных уловок собеседника</h3><ol><li>смена темы;</li><li>абстрактные слова без конкретного содержания;</li><li>необоснованное связывание причины и результата;</li><li>ложная альтернатива «или это, или то»;</li><li>подмена причины целью;</li><li>подмена причины поводом;</li><li>вывод по заведомо малому числу примеров;</li><li>подмена тезиса по ходу разговора;</li><li>неправомерное обобщение вроде «почти», «в целом»;</li><li>ссылка на безымянных «всех», «умных людей», «общество»;</li><li>переформулирование вашего вопроса в удобный для ответа;</li><li>объявление вопроса «недопустимым».</li></ol><div class="int162Rule">Контрприём не в том, чтобы «победить» героя. Верните вопрос: повторите иначе, сузьте его до пропущенной части, попросите конкретику, имя, цифру или основание утверждения.</div>`,q:'На вопрос «Почему проект провалился?» герой рассказывает, чего команда хотела добиться. Что это?',opts:['Ответ о причине','Подмена причины целью','Переходный вопрос'],correct:1},
    publish:{title:'После интервью: живой текст, заголовок и согласование',intro:'Расшифровка — сырьё; публикация требует отбора и редакторской работы.',body:`<h3>Что сохранять после разговора</h3><ul><li>новую фактуру и объяснения;</li><li>точные сильные фразы;</li><li>места, которые нужно проверить;</li><li>вопросы, которые надо дозадать;</li><li>для текстового интервью — важные наблюдаемые реакции, паузы, жесты, действия и детали места.</li></ul><div class="int162Rule">Репортажные элементы допустимы, если журналист реально их видел. Придумывать смех, нервозность, жесты или атмосферу нельзя.</div><h3>Упаковка</h3><p>Заголовок может быть яркой цитатой, но её смысл нельзя искажать ради громкости. Другой вариант — имя / роль героя + тема разговора. Лид объясняет, с кем и о чём вы говорили или по какому поводу состоялось интервью.</p><p>Устную речь можно чистить от повторов и речевого мусора, не меняя смысл.</p><div class="int162Warn"><b>Согласование:</b> если вы договорились его проводить, заранее определите предмет и срок. Проверка ответов не должна незаметно превращаться в переписывание журналистских вопросов, заголовка и собственной фактуры автора.</div>`,q:'Что нельзя делать с цитатой в заголовке?',opts:['Сократить её без изменения смысла','Искажать смысл ради более громкой фразы','Указать рядом имя героя'],correct:1}
  };

  const guestHints={expert:'Эксперт: просите простые объяснения и отделяйте главное от специальных деталей.',star:'Медийный человек: ищите личный опыт за публичным образом.',official:'Чиновник: спрашивайте о результате, ответственности, сроках и том, что не получилось.',politician:'Политик: требуйте конкретику и основания утверждений; возвращайте к вопросу.',hero:'Герой события: говорите просто, помогайте восстановить сцены без давления.',other:'Подберите тактику под роль человека в теме.'};
  const formatHints={personal:'Лично: видны реакции и среда; заранее проверьте место, разрешения и запись.',sync:'Звонок / видео: можно уточнять сразу; проверьте связь и резервную запись.',async:'Список вопросов: удобно, но меньше живых уточнений; договоритесь о возможности дозадать вопросы.'};
  function ch(label,key,val,current){return `<button type="button" class="int162Choice ${current===val?'active':''}" data-int162-choice="${key}" data-int162-value="${val}">${label}</button>`}

  function patchHub(){
    const hub=document.getElementById('interviewCourse160');if(!hub||!hub.innerHTML||hub.querySelector('#int162Method'))return;
    const work=hub.querySelector('.int160Work');if(!work)return;const box=document.createElement('div');box.id='int162Method';box.className='int162Box';
    box.innerHTML=`<div class="meta">Расширенная матчасть MMT</div><h3>До реального разговора</h3><div class="int162Cards">${Object.entries(lessons).map(([id,l])=>`<button class="int162Card ${I.v162[id]?'done':''}" data-int162-lesson="${id}"><b>${safe(l.title)}</b><small>${safe(l.intro)}</small></button>`).join('')}</div>`;work.before(box);
  }
  function openLesson(id){const l=lessons[id];if(!l)return;const answer=I.v162[id+'Answer'];lesson.dataset.int162Lesson=id;lesson.innerHTML=`<div class="eye">Интервью · методика MMT</div><div class="int162LessonHero"><div class="meta">расширенный блок</div><h2>${safe(l.title)}</h2><p>${safe(l.intro)}</p></div><div class="int162Box">${l.body}</div><div class="int162Box"><div class="meta">Быстрая проверка</div><h3>${safe(l.q)}</h3>${l.opts.map((o,i)=>`<button class="int162Option ${answer===i?(i===l.correct?'correct':'wrong'):''}" data-int162-answer="${i}">${safe(o)}</button>`).join('')}${answer!==undefined?`<div class="int162Hint">${answer===l.correct?'Верно. Можно завершать блок.':'Пока нет. Вернитесь к правилу выше.'}</div>`:''}</div><div class="int160Actions">${answer===l.correct?'<button class="btn" data-int162-complete>Завершить блок</button>':''}<button class="btn secondary" data-int162-hub>← К интервью</button></div>`;go('interviewLesson162')}

  function patchPrep(){
    const s=document.getElementById('interviewPrep160');if(!s||!s.innerHTML||s.querySelector('#int162Prep'))return;const first=s.querySelector('.int160Section');if(!first)return;const x=document.createElement('div');x.id='int162Prep';x.className='int160Section';x.innerHTML=`<h3>0. Стратегия разговора</h3>
      <div class="int160Field"><label>Вид интервью</label><div class="int162Choices">${ch('Информационное','interviewType','info',I.prep.interviewType)}${ch('Оперативное','interviewType','operational',I.prep.interviewType)}${ch('Расследование','interviewType','investigation',I.prep.interviewType)}${ch('Портрет','interviewType','portrait',I.prep.interviewType)}</div><div class="int162Hint">Оперативное интервью обычно является частью другого материала, а не большой самостоятельной публикацией.</div></div>
      <div class="int160Field"><label>Тип собеседника</label><div class="int162Choices">${ch('Эксперт','guestType','expert',I.prep.guestType)}${ch('Медийный','guestType','star',I.prep.guestType)}${ch('Чиновник','guestType','official',I.prep.guestType)}${ch('Политик','guestType','politician',I.prep.guestType)}${ch('Герой события','guestType','hero',I.prep.guestType)}${ch('Другое','guestType','other',I.prep.guestType)}</div><div class="int162Hint" data-int162-guest>${safe(guestHints[I.prep.guestType]||'Выберите роль — подскажем тактику.')}</div></div>
      <div class="int160Field"><label>Формат</label><div class="int162Choices">${ch('Лично','format','personal',I.prep.format)}${ch('Звонок / видео','format','sync',I.prep.format)}${ch('Список вопросов','format','async',I.prep.format)}</div><div class="int162Hint" data-int162-format>${safe(formatHints[I.prep.format]||'Выберите формат разговора.')}</div></div>
      <label class="int160Check"><input type="checkbox" data-int162-prep-check="knowsInterview" ${I.prep.knowsInterview?'checked':''}>Собеседник знает, что это журналистское интервью для публикации.</label>
      <label class="int160Check"><input type="checkbox" data-int162-prep-check="knowsTopic" ${I.prep.knowsTopic?'checked':''}>Основная тема / важный эпизод разговора обозначены заранее.</label>
      <div class="int160Field"><label>О чём договорились: место, время, запись, съёмка, ограничения?</label><textarea class="textarea" data-int162-prep="agreement">${safe(I.prep.agreement||'')}</textarea></div>
      <div class="int160Field"><label>Резервный план записи</label><textarea class="textarea" data-int162-prep="backup" placeholder="Второй диктофон / телефон / локальная запись / подробные заметки">${safe(I.prep.backup||'')}</textarea></div>`;first.before(x);
  }
  function patchQuestions(){const s=document.getElementById('interviewQuestions160');if(!s||!s.innerHTML||s.querySelector('#int162Questions'))return;const a=s.querySelector('.int160Actions');if(!a)return;const x=document.createElement('div');x.id='int162Questions';x.className='int160Section';x.innerHTML=`<h3>3. Управляющие и запасные вопросы</h3>
    <div class="int160Field"><label>Открывающий вопрос</label><textarea class="textarea" data-int162-q="opening">${safe(I.questions.opening||'')}</textarea></div>
    <div class="int160Field"><label>Переходы между блоками</label><textarea class="textarea" data-int162-q="transitions">${safe(I.questions.transitions||'')}</textarea></div>
    <div class="int160Field"><label>Как вернёте собеседника, если он уйдёт от вопроса?</label><textarea class="textarea" data-int162-q="returnPlan">${safe(I.questions.returnPlan||'')}</textarea></div>
    <div class="int160Field"><label>Закрытый вопрос на случай, если нужен ясный ответ</label><textarea class="textarea" data-int162-q="closedFallback">${safe(I.questions.closedFallback||'')}</textarea></div>
    <div class="int160Field"><label>Чувствительная тема: нужен ли непрямой вопрос?</label><textarea class="textarea" data-int162-q="indirect">${safe(I.questions.indirect||'')}</textarea></div>
    <label class="int160Check"><input type="checkbox" data-int162-q-check="oneIdea" ${I.questions.oneIdea?'checked':''}>Один основной вопрос — одна главная мысль.</label>
    <label class="int160Check"><input type="checkbox" data-int162-q-check="neutral" ${I.questions.neutral?'checked':''}>Я не подсказываю желаемый ответ и не вкладываю в вопрос предположение.</label>
    <label class="int160Check"><input type="checkbox" data-int162-q-check="evidence" ${I.questions.evidence?'checked':''}>К важным утверждениям готовы уточнения про пример, доказательство, цифру или источник.</label>`;a.before(x)}
  function patchTalk(){const s=document.getElementById('interviewTalk160');if(!s||!s.innerHTML||s.querySelector('#int162Talk'))return;const a=s.querySelector('.int160Actions');if(!a)return;const x=document.createElement('div');x.id='int162Talk';x.className='int160Section';x.innerHTML=`<h3>4. Поведение героя и управление разговором</h3>
    <div class="int160Field"><label>Какие важные реакции, паузы, действия или детали места вы наблюдали?</label><textarea class="textarea" data-int162-talk="nonverbal" placeholder="Только то, что реально видели / слышали">${safe(I.talk.nonverbal||'')}</textarea></div>
    <div class="int160Field"><label>Где собеседник уходил от ответа или говорил слишком общо?</label><textarea class="textarea" data-int162-talk="evasions">${safe(I.talk.evasions||'')}</textarea></div>
    <div class="int160Field"><label>Как вы вернули разговор к сути?</label><textarea class="textarea" data-int162-talk="returns">${safe(I.talk.returns||'')}</textarea></div>
    <div class="int160Field"><label>Какой сильный ответ появился благодаря уточнению?</label><textarea class="textarea" data-int162-talk="followupWin">${safe(I.talk.followupWin||'')}</textarea></div>
    <label class="int160Check"><input type="checkbox" data-int162-talk-check="backupWorked" ${I.talk.backupWorked?'checked':''}>Основная запись сохранилась или есть резервная запись / подробные заметки.</label>`;a.before(x)}

  const DB='mmt-dvi-interview-media-v1',STORE='media';function openDB(){return new Promise((res,rej)=>{const q=indexedDB.open(DB,1);q.onupgradeneeded=()=>{if(!q.result.objectStoreNames.contains(STORE))q.result.createObjectStore(STORE,{keyPath:'id'})};q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}async function putBlob(id,blob){const db=await openDB();return new Promise((res,rej)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put({id,blob});tx.oncomplete=()=>{db.close();res()};tx.onerror=()=>{db.close();rej(tx.error)}})}async function getBlob(id){if(!id)return null;const db=await openDB();return new Promise((res,rej)=>{const q=db.transaction(STORE,'readonly').objectStore(STORE).get(id);q.onsuccess=()=>{db.close();res(q.result?.blob||null)};q.onerror=()=>{db.close();rej(q.error)}})}async function delBlob(id){if(!id)return;const db=await openDB();return new Promise((res,rej)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).delete(id);tx.oncomplete=()=>{db.close();res()};tx.onerror=()=>{db.close();rej(tx.error)}})}
  async function renderPhoto(){const b=document.querySelector('[data-int162-photo-box]');if(!b)return;const p=I.media.heroPhoto;b.innerHTML='';if(!p?.id)return;const blob=await getBlob(p.id).catch(()=>null),url=blob?URL.createObjectURL(blob):'';b.innerHTML=`<div class="int162Photo">${url?`<img src="${url}" alt="Фото героя">`:'<div class="int162Warn">Файл фото не найден на этом устройстве.</div>'}<div class="int160Field"><label>Источник / автор фото</label><input class="input" data-int162-photo-source value="${safe(p.source||'')}" placeholder="Личный архив / фотограф / издание / источник"></div><button class="int162Delete" data-int162-photo-delete>Удалить фото</button></div>`}
  function patchDraft(){const s=document.getElementById('interviewDraft160');if(!s||!s.innerHTML||s.querySelector('#int162Draft'))return;const text=s.querySelector('[data-int160-draft="text"]'),sec=text?.closest('.int160Section');if(!sec)return;const lead=s.querySelector('[data-int160-draft="lead"]'),lab=lead?.closest('.int160Field')?.querySelector('label');if(lab&&lab.textContent.indexOf('Лид:')!==0)lab.textContent='Лид: кто герой, о чём вы говорили и / или по какому поводу состоялось интервью?';const x=document.createElement('div');x.id='int162Draft';x.className='int160Section';x.innerHTML=`<h3>Упаковка текстового интервью</h3>
    <div class="int160Field"><label>Тип заголовка</label><div class="int162Choices">${ch('Яркая цитата','headlineType','quote',I.draft.headlineType)}${ch('Имя / роль + темы','headlineType','descriptor',I.draft.headlineType)}</div><div class="int162Hint">Цитатный заголовок не должен искажать смысл слов героя ради громкости.</div></div>
    <div class="int160Field"><label>Репортажные элементы</label><textarea class="textarea" data-int162-draft="reportage" placeholder="Место, жест, пауза, действие — только наблюдаемое лично">${safe(I.draft.reportage||'')}</textarea></div>
    <div class="int160Field"><label>Согласование</label><select class="input" data-int162-draft="approval"><option value="none" ${I.draft.approval==='none'?'selected':''}>Не договаривались</option><option value="planned" ${I.draft.approval==='planned'?'selected':''}>Договорились согласовать ответы</option><option value="sent" ${I.draft.approval==='sent'?'selected':''}>Отправлено</option><option value="approved" ${I.draft.approval==='approved'?'selected':''}>Ответы согласованы</option><option value="changes" ${I.draft.approval==='changes'?'selected':''}>Есть правки — проверить смысл</option></select></div>
    <h3 style="margin-top:14px">Фото героя / обложка</h3><label class="int162Upload">＋ Загрузить фото<input type="file" accept="image/*" data-int162-photo-input></label><div class="int162Hint">Для фото обязательно укажите источник или автора.</div><div data-int162-photo-box></div><div id="int162SubmitStatus"></div>`;sec.before(x);renderPhoto()}

  function sync(){document.querySelectorAll('[data-int162-prep]').forEach(e=>I.prep[e.dataset.int162Prep]=e.value.trim());document.querySelectorAll('[data-int162-prep-check]').forEach(e=>I.prep[e.dataset.int162PrepCheck]=e.checked);document.querySelectorAll('[data-int162-q]').forEach(e=>I.questions[e.dataset.int162Q]=e.value.trim());document.querySelectorAll('[data-int162-q-check]').forEach(e=>I.questions[e.dataset.int162QCheck]=e.checked);document.querySelectorAll('[data-int162-talk]').forEach(e=>I.talk[e.dataset.int162Talk]=e.value.trim());document.querySelectorAll('[data-int162-talk-check]').forEach(e=>I.talk[e.dataset.int162TalkCheck]=e.checked);document.querySelectorAll('[data-int162-draft]').forEach(e=>I.draft[e.dataset.int162Draft]=e.value.trim());const ps=document.querySelector('[data-int162-photo-source]');if(ps&&I.media.heroPhoto)I.media.heroPhoto.source=ps.value.trim();persist()}
  function patchAll(){patchHub();patchPrep();patchQuestions();patchTalk();patchDraft()}

  document.addEventListener('click',e=>{const l=e.target.closest('[data-int162-lesson]');if(l){e.preventDefault();openLesson(l.dataset.int162Lesson);return}const a=e.target.closest('[data-int162-answer]');if(a){e.preventDefault();const id=lesson.dataset.int162Lesson;I.v162[id+'Answer']=Number(a.dataset.int162Answer);persist();openLesson(id);return}if(e.target.closest('[data-int162-complete]')){e.preventDefault();const id=lesson.dataset.int162Lesson;if(I.v162[id+'Answer']!==lessons[id].correct)return;I.v162[id]=true;persist();go('interviewCourse160');setTimeout(patchHub,0);return}if(e.target.closest('[data-int162-hub]')){e.preventDefault();go('interviewCourse160');setTimeout(patchHub,0);return}const c=e.target.closest('[data-int162-choice]');if(c){e.preventDefault();const k=c.dataset.int162Choice,v=c.dataset.int162Value;if(k==='headlineType')I.draft[k]=v;else I.prep[k]=v;persist();document.querySelectorAll(`[data-int162-choice="${k}"]`).forEach(b=>b.classList.toggle('active',b.dataset.int162Value===v));if(k==='guestType'){const b=document.querySelector('[data-int162-guest]');if(b)b.textContent=guestHints[v]}if(k==='format'){const b=document.querySelector('[data-int162-format]');if(b)b.textContent=formatHints[v]}return}if(e.target.closest('[data-int162-photo-delete]')){e.preventDefault();const id=I.media.heroPhoto?.id;if(id)delBlob(id).catch(()=>{});I.media.heroPhoto=null;persist();renderPhoto()}},true);
  document.addEventListener('change',async e=>{if(e.target.matches('[data-int162-photo-input]')){const f=e.target.files?.[0];if(f&&f.type.startsWith('image/')){if(f.size>12*1024*1024)return notify('Фото больше 12 МБ');if(I.media.heroPhoto?.id)await delBlob(I.media.heroPhoto.id).catch(()=>{});const id='int-'+Date.now().toString(36);await putBlob(id,f);I.media.heroPhoto={id,name:f.name,source:''};persist();await renderPhoto()}e.target.value='';return}if(e.target.closest('[data-int162-prep],[data-int162-prep-check],[data-int162-q],[data-int162-q-check],[data-int162-talk],[data-int162-talk-check],[data-int162-draft],[data-int162-photo-source]'))sync()});
  document.addEventListener('input',e=>{if(e.target.closest('[data-int162-prep],[data-int162-q],[data-int162-talk],[data-int162-draft],[data-int162-photo-source]'))sync()});
  document.addEventListener('click',e=>{if(!e.target.closest('[data-int160-submit]'))return;sync();const crit=[],warn=[];if(!I.prep.interviewType)crit.push('выберите вид интервью');if(!I.prep.guestType)crit.push('укажите тип собеседника');if(!I.prep.format)crit.push('укажите формат разговора');if(!I.prep.knowsInterview)crit.push('подтвердите, что герой знает: это интервью для публикации');if(I.media.heroPhoto?.id&&!(I.media.heroPhoto.source||'').trim())crit.push('у загруженного фото нужен источник / автор');if(!I.prep.knowsTopic)warn.push('не отмечено, что тема обозначена заранее');if(!I.questions.returnPlan)warn.push('не продуман способ вернуть героя к вопросу');if(!I.questions.oneIdea||!I.questions.neutral)warn.push('не завершена самопроверка вопросов');const b=document.getElementById('int162SubmitStatus');if(crit.length){e.preventDefault();e.stopImmediatePropagation();if(b)b.innerHTML=`<div class="int162Submit bad"><b>Пока нельзя сдавать:</b><br>• ${crit.map(safe).join('<br>• ')}</div>`;notify('Закройте обязательные элементы подготовки интервью');return}if(b&&warn.length)b.innerHTML=`<div class="int162Submit warn"><b>Проверьте перед сдачей:</b><br>• ${warn.map(safe).join('<br>• ')}</div>`},true);
  const obs=new MutationObserver(()=>requestAnimationFrame(patchAll));obs.observe(main,{subtree:true,childList:true});setTimeout(patchAll,0);
})();