/* MMT ДВИ v0.16.3 — school-level text interview methodology expansion */
(function setupV0163(){
  if(typeof state==='undefined')return;
  const main=document.querySelector('main');if(!main)return;
  const VER='v0.16.3';const ver=document.querySelector('.ver');if(ver)ver.textContent=VER;document.title='MMT ДВИ — '+VER;
  state.v160Interview=state.v160Interview&&typeof state.v160Interview==='object'?state.v160Interview:{};
  const I=state.v160Interview;I.prep=I.prep||{};I.questions=I.questions||{};I.talk=I.talk||{};I.draft=I.draft||{};I.v163=I.v163||{};
  const safe=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const persist=()=>{try{localStorage.setItem('mmtV04',JSON.stringify(state))}catch(e){console.warn('[MMT v0.16.3]',e)}};
  const notify=m=>{if(typeof toast==='function')toast(m)};const go=id=>{if(typeof window.go==='function')window.go(id)};

  const css=document.createElement('style');css.id='mmt-v0163-css';css.textContent=`
    .int163Box{background:#fff;border:1px solid var(--line);border-radius:18px;padding:14px;margin:10px 0}.int163Box h3{font-size:18px;margin:0 0 8px}.int163Box p,.int163Box li{font-size:12px;line-height:1.5}.int163Box ul{padding-left:20px}.int163Grid{display:grid;gap:8px}.int163Card{width:100%;text-align:left;background:#fff;border:1px solid var(--line);border-radius:15px;padding:12px;color:var(--ink)}.int163Card.done{border-color:#9cbe9d}.int163Card b{display:block;font-size:13px}.int163Card small{display:block;color:var(--soft);font-size:10px;line-height:1.4;margin-top:4px}
    .int163Hero{background:#0c0c0c;color:#fff;border-radius:20px;padding:16px;margin:10px 0}.int163Hero .meta{color:#bbb}.int163Hero h2{font-size:25px;margin:5px 0}.int163Hero p{font-size:12px;line-height:1.45;color:#d0d0d0}.int163Rule{border-left:4px solid var(--o);background:var(--os);border-radius:0 13px 13px 0;padding:9px 11px;margin:10px 0;font-size:11px;line-height:1.45}.int163Tip{background:#eef5ee;border:1px solid #b5cbb5;border-radius:13px;padding:10px 11px;font-size:11px;line-height:1.45;margin:9px 0}.int163Warn{background:#fff3ea;border:1px solid #eab896;border-radius:13px;padding:10px 11px;font-size:11px;line-height:1.45;margin:9px 0}
    .int163ChoiceRow{display:flex;gap:6px;flex-wrap:wrap;margin:7px 0}.int163Choice{border:1px solid var(--line);background:#fff;border-radius:11px;padding:8px 9px;font-size:10px;font-weight:800;color:var(--ink)}.int163Choice.active{border-color:var(--o);background:var(--os)}.int163Hint{font-size:10px;color:var(--soft);line-height:1.42;margin-top:5px}.int163Option{width:100%;background:#fff;border:1px solid var(--line);border-radius:12px;padding:10px;margin:5px 0;text-align:left;font-size:11px;color:var(--ink)}.int163Option.correct{background:#eef7ee;border-color:#6aa46c}.int163Option.wrong{background:#faeeee;border-color:#c36e6e}.int163Details{background:var(--muted);border-radius:13px;padding:10px 11px;margin:9px 0}.int163Details summary{font-size:11px;font-weight:800;cursor:pointer}.int163Details li{font-size:10px;line-height:1.4;margin:4px 0}
  `;document.head.appendChild(css);

  let lesson=document.getElementById('interviewLesson163');if(!lesson){lesson=document.createElement('section');lesson.id='interviewLesson163';lesson.className='screen';main.appendChild(lesson)}

  const lessons={
    realistic:{title:'Кого реально может интервьюировать школьник',intro:'Сильное интервью не требует знаменитости или академика федерального уровня.',body:`<h3>Не гонитесь за статусом</h3><p>Для учебного текстового интервью важнее не громкое имя, а <b>связь человека с темой</b> и возможность получить от него новую фактуру.</p><ul><li>организатор локального события;</li><li>тренер, педагог, руководитель кружка или студии;</li><li>сотрудник музея, библиотеки, НКО, локального медиа;</li><li>практик небольшой компании или проекта;</li><li>участник события или человек с необычным опытом;</li><li>местный специалист, если его компетентность по теме понятна.</li></ul><div class="int163Rule">Журналист не обязан быть экспертом. Его задача — подготовиться достаточно, чтобы задавать понятные вопросы, замечать непонятное и вести читателя к новому пониманию темы.</div><p>Если вы называете человека экспертом, объясните, <b>на чём основана его компетентность</b>: профессия, должность, практика, исследование, участие в процессе. Медийность сама по себе экспертизу не создаёт.</p>`,q:'Для школьного интервью о том, как работает городской музей, кто может быть сильным героем?',opts:['Только известный федеральный историк','Сотрудник музея, который реально работает с экспозицией и может объяснить процессы','Любой знакомый, даже если он не связан с музеем'],correct:1},
    event:{title:'Событийное интервью: увидеть событие глазами человека',intro:'Участник или очевидец ценен своим опытом события, а не обязательной экспертностью.',body:`<h3>Фокус — событие и личный опыт</h3><p>Если собеседник был участником или очевидцем, разговор строится вокруг того, <b>что происходило и как он это воспринимал</b>. Биография человека нужна только там, где помогает понять его роль в событии.</p><p>Удобная логика — восстановить хронологию: что было до, что произошло в ключевой момент, что человек видел и чувствовал, что произошло после.</p><div class="int163Warn"><b>Важно:</b> память и стресс могут искажать восприятие. Один очевидец не заменяет проверку фактов по другим источникам. Его ценность — возможность показать эмоциональный опыт и взгляд изнутри.</div><p>Если собеседник одновременно компетентный специалист или организатор, можно отдельно задавать вопросы по его профессиональной роли. Но организатор заинтересован в хорошем впечатлении о мероприятии — это тоже нужно учитывать.</p>`,q:'Что главное получить от обычного участника события?',opts:['Полную и окончательную реконструкцию события как единственный источник истины','Его конкретный опыт, наблюдения и восприятие происходившего','Экспертный прогноз по отрасли, даже если он не специалист'],correct:1},
    meaning:{title:'Разговор должен создать новое',intro:'Интервью — не устный пересказ того, что уже найдено в интернете.',body:`<h3>Новизна бывает разной</h3><ul><li>новый факт или подробность;</li><li>объяснение причины или решения;</li><li>личная история, которой раньше не было в открытых источниках;</li><li>новая перспектива на знакомую тему;</li><li>уточнение противоречия;</li><li>мысль, которая появилась благодаря последовательности вопросов и «добивкам».</li></ul><div class="int163Rule">Подготовка нужна не для того, чтобы показать гостю, сколько вы уже знаете. Она нужна, чтобы не тратить разговор на справку и быстрее добраться до того, чего вы пока не знаете.</div><p>Не придумывайте историю за собеседника вопросом вроде «Было ли такое, что…», если для такого предположения нет основания. Лучше спросить открыто о конкретном опыте, трудности, решении или моменте.</p>`,q:'Какой результат лучше показывает, что интервью состоялось как журналистская работа?',opts:['Герой повторил свою биографию и общеизвестные факты','Разговор дал новую подробность, объяснение или перспективу, которой не было в подготовительных источниках','Журналист задал все вопросы строго по списку'],correct:1},
    structure:{title:'Одна главная задача — несколько смысловых блоков',intro:'Большое текстовое интервью не должно быть ни однотемным допросом, ни хаотичным разговором обо всём.',body:`<h3>Как собрать объёмную беседу</h3><p>Для приложения держим <b>одну главную журналистскую задачу</b> и разбиваем её на 3–5 смысловых блоков.</p><ul><li>В портрете блоки могут раскрывать разные стороны человека: путь, работа, конфликт, страхи, планы.</li><li>В проблемно-ситуативном или экспертном разговоре блоки раскрывают разные аспекты одной проблемы: что произошло, почему, последствия, спорные места, что дальше.</li><li>В событийном интервью блоки могут идти по хронологии события.</li></ul><p>Иногда в интервью могут быть <b>несколько героев</b>, если каждый добавляет свою роль и помогает раскрыть одну общую тему.</p><div class="int163Tip"><b>Учебный пример:</b> в информационном интервью о сезонной распродаже сначала говорит хозяйка магазина, затем покупательница. Это две разные позиции внутри одного повода — организатор и аудитория.</div>`,q:'Как лучше построить большое проблемное интервью?',opts:['Одна общая тема и 3–5 связанных смысловых блоков','Десять случайных тем, чтобы разговор казался длиннее','Один вопрос без уточнений на весь материал'],correct:0}
  };

  function openLesson(id){const l=lessons[id];if(!l)return;const ans=I.v163[id+'Answer'];lesson.dataset.int163Lesson=id;lesson.innerHTML=`<div class="eye">Интервью · методика MMT</div><div class="int163Hero"><div class="meta">дополнение для текстового интервью</div><h2>${safe(l.title)}</h2><p>${safe(l.intro)}</p></div><div class="int163Box">${l.body}</div><div class="int163Box"><div class="meta">Быстрая проверка</div><h3>${safe(l.q)}</h3>${l.opts.map((o,i)=>`<button class="int163Option ${ans===i?(i===l.correct?'correct':'wrong'):''}" data-int163-answer="${i}">${safe(o)}</button>`).join('')}${ans!==undefined?`<div class="int163Hint">${ans===l.correct?'Верно. Можно завершать блок.':'Пока нет. Вернитесь к принципу выше.'}</div>`:''}</div><div class="int160Actions">${ans===l.correct?'<button class="btn" data-int163-complete>Завершить блок</button>':''}<button class="btn secondary" data-int163-hub>← К интервью</button></div>`;go('interviewLesson163')}

  function choice(label,key,val,current){return `<button type="button" class="int163Choice ${current===val?'active':''}" data-int163-choice="${key}" data-int163-value="${val}">${label}</button>`}

  function patchHub(){const hub=document.getElementById('interviewCourse160');if(!hub||!hub.innerHTML)return;const hero=hub.querySelector('.int160Hero');if(hero&&!hero.querySelector('.int163TextOnly')){const n=document.createElement('div');n.className='int163TextOnly int163Tip';n.innerHTML='<b>В этом модуле итог — только текстовое интервью.</b><br>Личная встреча, звонок или список вопросов — это способы провести разговор. Аудио- и видеопроизводство здесь не оцениваем.';hero.appendChild(n)}if(hub.querySelector('#int163Method'))return;const anchor=hub.querySelector('#int162Method')||hub.querySelector('.int160Work');if(!anchor)return;const box=document.createElement('div');box.id='int163Method';box.className='int163Box';box.innerHTML=`<div class="meta">Ещё 4 важных блока</div><h3>Интервью для школьника: реалистично и по-журналистски</h3><div class="int163Grid">${Object.entries(lessons).map(([id,l])=>`<button class="int163Card ${I.v163[id]?'done':''}" data-int163-lesson="${id}"><b>${safe(l.title)}</b><small>${safe(l.intro)}</small></button>`).join('')}</div>`;anchor.after(box)}

  function patchPrep(){const s=document.getElementById('interviewPrep160');if(!s||!s.innerHTML)return;const info=s.querySelector('[data-int162-choice="interviewType"][data-int162-value="info"]');if(info&&info.textContent!=='Информационное / событийное')info.textContent='Информационное / событийное';const formatLabel=s.querySelector('[data-int162-choice="format"]')?.closest('.int160Field')?.querySelector('label');if(formatLabel&&formatLabel.textContent==='Формат')formatLabel.textContent='Как проведёте разговор?';if(s.querySelector('#int163Prep'))return;const firstOriginal=s.querySelector('.int160Section:not(#int162Prep)');if(!firstOriginal)return;const x=document.createElement('div');x.id='int163Prep';x.className='int160Section';x.innerHTML=`<h3>0.5. Реалистичность героя</h3><div class="int163Tip"><b>Не нужен «суперэксперт».</b><br>Для школьного материала достаточно доступного человека, который действительно связан с темой и может дать новую фактуру. Статус важен меньше, чем релевантность и реальный разговор.</div>
    <div class="int160Field"><label>Сколько собеседников планируется?</label><div class="int163ChoiceRow">${choice('Один','heroScope','one',I.prep.heroScope)}${choice('Несколько','heroScope','multi',I.prep.heroScope)}</div></div>
    <div class="int160Field"><label>Почему с этим человеком реально можно договориться?</label><textarea class="textarea" data-int163-prep="accessReason" placeholder="Есть контакт, можно написать через организацию, встретить на событии, попросить через пресс-службу…">${safe(I.prep.accessReason||'')}</textarea></div>
    <div class="int160Field"><label>Если собеседник заявлен как эксперт — чем подтверждается его компетентность?</label><textarea class="textarea" data-int163-prep="competence" placeholder="Профессия, должность, практика, исследование, участие в процессе. Если это не эксперт — так и напишите.">${safe(I.prep.competence||'')}</textarea></div>
    <div class="int160Field" data-int163-extra-wrap style="${I.prep.heroScope==='multi'?'':'display:none'}"><label>Дополнительные собеседники и зачем нужен каждый</label><textarea class="textarea" data-int163-prep="extraHeroes" placeholder="Например: организатор — как всё устроено; участник — личный опыт">${safe(I.prep.extraHeroes||'')}</textarea></div>
    <div class="int160Field"><label>Если разговор связан с конкретным событием — как герой с ним связан?</label><textarea class="textarea" data-int163-prep="eventRole" placeholder="Участник, очевидец, организатор, специалист; что именно он видел / делал">${safe(I.prep.eventRole||'')}</textarea></div>`;firstOriginal.before(x)}

  function patchQuestions(){const s=document.getElementById('interviewQuestions160');if(!s||!s.innerHTML)return;const blocks=s.querySelector('[data-int160-q="blocks"]');const lab=blocks?.closest('.int160Field')?.querySelector('label');if(lab&&lab.textContent!=='На какие 3–5 смысловых блока / аспекта вы разделите разговор?')lab.textContent='На какие 3–5 смысловых блока / аспекта вы разделите разговор?';if(s.querySelector('#int163Questions'))return;const a=s.querySelector('.int160Actions');if(!a)return;const x=document.createElement('div');x.id='int163Questions';x.className='int160Section';x.innerHTML=`<h3>4. Новизна и «добивки»</h3>
    <div class="int160Field"><label>Главная проблема / журналистская задача одним предложением</label><textarea class="textarea" data-int163-q="coreTask" placeholder="Что читатель должен понять благодаря этому разговору?">${safe(I.questions.coreTask||'')}</textarea></div>
    <div class="int160Field"><label>Что вы надеетесь получить нового, чего нет в обычной справке о герое?</label><textarea class="textarea" data-int163-q="novelty" placeholder="Новый факт, объяснение решения, личная история, неизвестная деталь, новая перспектива…">${safe(I.questions.novelty||'')}</textarea></div>
    <div class="int160Field"><label>Какие ответы уже найдены заранее и не стоит спрашивать в лоб?</label><textarea class="textarea" data-int163-q="alreadyKnown" placeholder="Биография, должность, известные даты, уже опубликованные заявления…">${safe(I.questions.alreadyKnown||'')}</textarea></div>
    <div class="int163Warn"><b>Осторожно с шаблоном «Было ли такое, что…».</b><br>Он легко подсовывает гостю придуманную журналистом историю. Если нет основания, спрашивайте о реальном опыте открыто и ждите, что собеседник сам назовёт конкретный эпизод.</div>
    <details class="int163Details"><summary>Банк формулировок — только для разгона, не копировать механически</summary><ul><li>Что привело вас именно к…?</li><li>Какими были первые шаги?</li><li>Что было самым сложным?</li><li>Как вы приняли это решение?</li><li>Что изменилось после…?</li><li>Какие подводные камни есть в этой сфере?</li><li>Как окружающие восприняли эту перемену?</li><li>Какой момент стал переломным?</li><li>Что сейчас вы сделали бы иначе?</li><li>Что в этой теме чаще всего понимают неправильно?</li></ul></details>
    <label class="int160Check"><input type="checkbox" data-int163-q-check="notTemplate" ${I.questions.notTemplate?'checked':''}>Я не собираю интервью из универсальных вопросов без привязки к герою и теме.</label>
    <label class="int160Check"><input type="checkbox" data-int163-q-check="followupReady" ${I.questions.followupReady?'checked':''}>Я готов(а) делать «добивки»: уточнять конкретику из ответа, даже если такого вопроса не было в плане.</label>`;a.before(x)}

  function patchTalk(){const s=document.getElementById('interviewTalk160');if(!s||!s.innerHTML||s.querySelector('#int163Talk'))return;const a=s.querySelector('.int160Actions');if(!a)return;const x=document.createElement('div');x.id='int163Talk';x.className='int160Section';x.innerHTML=`<h3>5. Что изменилось после разговора</h3>
    <div class="int160Field"><label>Что нового вы теперь понимаете о теме благодаря интервью?</label><textarea class="textarea" data-int163-talk="newMeaning" placeholder="Не только новый факт: это может быть объяснение, перспектива, связь между событиями, неожиданная история">${safe(I.talk.newMeaning||'')}</textarea></div>
    <div class="int160Field" data-int163-event-wrap><label>Если это событийное интервью: восстановите ключевые моменты глазами героя</label><textarea class="textarea" data-int163-talk="eventTimeline" placeholder="Что было до → ключевой момент → что герой видел / чувствовал → что было после">${safe(I.talk.eventTimeline||'')}</textarea><div class="int163Hint">Это опыт собеседника, а не единственная версия фактов. Важные обстоятельства проверяйте отдельно.</div></div>
    <div class="int160Field" data-int163-multi-wrap style="${I.prep.heroScope==='multi'?'':'display:none'}"><label>Если героев несколько — что добавил каждый?</label><textarea class="textarea" data-int163-talk="multiRoles">${safe(I.talk.multiRoles||'')}</textarea></div>`;a.before(x)}

  function patchDraft(){const s=document.getElementById('interviewDraft160');if(!s||!s.innerHTML||s.querySelector('#int163DraftNote'))return;const hero=s.querySelector('.int160StageHero');if(!hero)return;const n=document.createElement('div');n.id='int163DraftNote';n.className='int163Rule';n.innerHTML='<b>Финальный продукт этого модуля — текст.</b><br>Можно проводить разговор лично, по видеосвязи или письменно, но в приложение вы собираете журналистскую текстовую публикацию: заголовок, лид, отобранные вопросы и ответы, при необходимости — наблюдаемые репортажные детали и фото с источником.';hero.after(n)}

  function sync(){document.querySelectorAll('[data-int163-prep]').forEach(e=>I.prep[e.dataset.int163Prep]=e.value.trim());document.querySelectorAll('[data-int163-q]').forEach(e=>I.questions[e.dataset.int163Q]=e.value.trim());document.querySelectorAll('[data-int163-q-check]').forEach(e=>I.questions[e.dataset.int163QCheck]=e.checked);document.querySelectorAll('[data-int163-talk]').forEach(e=>I.talk[e.dataset.int163Talk]=e.value.trim());persist()}
  function patchAll(){patchHub();patchPrep();patchQuestions();patchTalk();patchDraft()}

  document.addEventListener('click',e=>{const l=e.target.closest('[data-int163-lesson]');if(l){e.preventDefault();openLesson(l.dataset.int163Lesson);return}const a=e.target.closest('[data-int163-answer]');if(a){e.preventDefault();const id=lesson.dataset.int163Lesson;I.v163[id+'Answer']=Number(a.dataset.int163Answer);persist();openLesson(id);return}if(e.target.closest('[data-int163-complete]')){e.preventDefault();const id=lesson.dataset.int163Lesson;if(I.v163[id+'Answer']!==lessons[id].correct)return;I.v163[id]=true;persist();go('interviewCourse160');setTimeout(patchHub,0);return}if(e.target.closest('[data-int163-hub]')){e.preventDefault();go('interviewCourse160');setTimeout(patchHub,0);return}const c=e.target.closest('[data-int163-choice]');if(c){e.preventDefault();const k=c.dataset.int163Choice,v=c.dataset.int163Value;I.prep[k]=v;persist();document.querySelectorAll(`[data-int163-choice="${k}"]`).forEach(b=>b.classList.toggle('active',b.dataset.int163Value===v));if(k==='heroScope'){const w=document.querySelector('[data-int163-extra-wrap]');if(w)w.style.display=v==='multi'?'':'none';const tw=document.querySelector('[data-int163-multi-wrap]');if(tw)tw.style.display=v==='multi'?'':'none'}return}},true);
  document.addEventListener('input',e=>{if(e.target.closest('[data-int163-prep],[data-int163-q],[data-int163-talk]'))sync()});
  document.addEventListener('change',e=>{if(e.target.closest('[data-int163-q-check],[data-int163-prep],[data-int163-q],[data-int163-talk]'))sync()});
  document.addEventListener('click',e=>{if(!e.target.closest('[data-int160-submit]'))return;sync();const warn=[];if(!I.prep.accessReason)warn.push('не объяснено, почему с выбранным героем реально можно договориться');if(I.prep.guestType==='expert'&&!I.prep.competence)warn.push('герой назван экспертом, но не указано, чем подтверждается компетентность');if(I.prep.interviewType==='info'&&!I.prep.eventRole)warn.push('для информационного / событийного разговора полезно указать роль героя в событии');if(I.prep.heroScope==='multi'&&!I.prep.extraHeroes)warn.push('выбрано несколько собеседников, но не объяснена роль каждого');if(!I.questions.coreTask)warn.push('не сформулирована одна главная журналистская задача');if(!I.questions.novelty)warn.push('не зафиксировано, какую новую информацию или перспективу должен дать разговор');if(!I.questions.notTemplate||!I.questions.followupReady)warn.push('не завершена самопроверка по шаблонным вопросам и «добивкам»');const b=document.getElementById('int162SubmitStatus');if(b&&warn.length&&!b.innerHTML)b.innerHTML=`<div class="int162Submit warn"><b>Перед сдачей ещё раз проверьте:</b><br>• ${warn.map(safe).join('<br>• ')}</div>`},true);
  const obs=new MutationObserver(()=>requestAnimationFrame(patchAll));obs.observe(main,{subtree:true,childList:true});setTimeout(patchAll,0);
})();