/* MMT ДВИ v0.16.0 — interview module, no AI */
(function setupV016(){
  if(typeof state==='undefined')return;
  const main=document.querySelector('main');if(!main)return;
  const VER='v0.16.0';const ver=document.querySelector('.ver');if(ver)ver.textContent=VER;document.title='MMT ДВИ — '+VER;
  const safe=s=>typeof esc==='function'?esc(String(s??'')):String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const persist=()=>{try{localStorage.setItem('mmtV04',JSON.stringify(state))}catch(e){console.warn('[MMT v0.16] persist failed',e)}};
  const notify=msg=>{if(typeof toast==='function')toast(msg)};const go=id=>{if(typeof window.go==='function')window.go(id)};

  state.v160Interview=state.v160Interview&&typeof state.v160Interview==='object'?state.v160Interview:{};
  const I=state.v160Interview;I.lessons=I.lessons||{};I.micro=I.micro||{};I.prep=I.prep||{};I.questions=I.questions||{};I.talk=I.talk||{};I.draft=I.draft||{};I.submitted=!!I.submitted;

  const css=document.createElement('style');css.id='mmt-v016-css';css.textContent=`
    .int160Hero{background:#0c0c0c;color:#fff;border-radius:22px;padding:18px;margin:10px 0}.int160Hero .meta{color:#bbb}.int160Hero h2{font-size:29px;margin:5px 0 7px}.int160Hero p{color:#d4d4d4;font-size:13px;line-height:1.5}.int160Tags{display:flex;gap:6px;flex-wrap:wrap;margin-top:12px}.int160Tags span{font-size:10px;border:1px solid #ffffff28;background:#ffffff12;border-radius:999px;padding:6px 8px}
    .int160Progress{background:var(--os);border-radius:17px;padding:13px;margin:10px 0}.int160List{display:grid;gap:8px;margin:10px 0}.int160Card{background:#fff;border:1px solid var(--line);border-radius:17px;padding:13px;text-align:left;color:var(--ink);width:100%}.int160Card.done{border-color:#9cbe9d}.int160Card b{font-size:14px;display:block}.int160Card small{display:block;color:var(--soft);font-size:11px;line-height:1.4;margin-top:4px}.int160Num{width:29px;height:29px;border-radius:9px;background:var(--muted);display:grid;place-items:center;font-size:11px;font-weight:800}.int160Status{font-size:9px;border-radius:999px;background:var(--muted);padding:5px 7px;white-space:nowrap}.int160Status.ok{background:#e8f3e8}
    .int160Work{background:#fff;border:2px solid var(--o);border-radius:19px;padding:14px;margin:13px 0}.int160Work h3{font-size:20px;margin:4px 0 7px}.int160Work p{font-size:12px;line-height:1.45;color:var(--soft)}
    .int160LessonHead,.int160StageHero{background:var(--os);border-radius:19px;padding:15px;margin:10px 0}.int160StageHero{background:#0c0c0c;color:#fff}.int160StageHero .meta{color:#bbb}.int160StageHero p{color:#d0d0d0;font-size:12px;line-height:1.45}.int160LessonHead h2,.int160StageHero h2{font-size:25px;margin:4px 0 7px}.int160Text,.int160Section{background:#fff;border:1px solid var(--line);border-radius:18px;padding:15px;margin:9px 0}.int160Text h3,.int160Section h3{font-size:18px;margin:0 0 8px}.int160Text p,.int160Text li{font-size:13px;line-height:1.53}.int160Text ul{padding-left:20px}.int160Rule{border-left:4px solid var(--o);padding:9px 12px;background:var(--os);border-radius:0 13px 13px 0;margin:10px 0;font-size:12px;line-height:1.45}
    .int160Micro{background:#fff;border:2px solid var(--o);border-radius:18px;padding:14px;margin:12px 0}.int160Option{width:100%;background:#fff;border:1px solid var(--line);border-radius:13px;padding:11px;margin:5px 0;text-align:left;font-size:12px;line-height:1.4;color:var(--ink)}.int160Option.correct{border-color:#6aa46c;background:#eef7ee}.int160Option.wrong{border-color:#c36e6e;background:#faeeee}.int160Feedback{font-size:12px;line-height:1.45;margin-top:8px;padding:9px 10px;border-radius:12px;background:var(--muted)}
    .int160Field{margin:12px 0}.int160Field label{display:block;font-size:11px;font-weight:800;margin-bottom:5px}.int160Field .input,.int160Field .textarea{width:100%;box-sizing:border-box}.int160Field .textarea{min-height:95px}.int160Field.long .textarea{min-height:210px}.int160Hint{font-size:10px;color:var(--soft);line-height:1.4;margin-top:5px}.int160Check{display:flex;gap:8px;align-items:flex-start;font-size:11px;line-height:1.4;margin:9px 0}.int160Check input{margin-top:2px;accent-color:var(--o)}.int160Actions{display:grid;gap:8px;margin:13px 0}.int160Actions .btn{margin:0}.int160Saved{text-align:center;color:var(--soft);font-size:10px;margin-top:7px}.int160Submitted{background:#eaf4ea;border:1px solid #aac8aa;border-radius:16px;padding:13px;margin:11px 0}.int160Submitted p{font-size:11px;line-height:1.45;margin:4px 0 0;color:var(--soft)}
    .route135Module.int160Open{cursor:pointer}.route135Module.int160Open .tag{background:var(--o);color:#0c0c0c}.int160Next{background:#fff;border:1px solid var(--line);border-radius:17px;padding:13px;margin:12px 0}.int160Next h3{font-size:18px;margin:3px 0 6px}.int160Next p{font-size:12px;line-height:1.45;color:var(--soft)}
  `;document.head.appendChild(css);

  function screen(id){let s=document.getElementById(id);if(!s){s=document.createElement('section');s.id=id;s.className='screen';main.appendChild(s)}return s}
  const hub=screen('interviewCourse160'),lessonScreen=screen('interviewLesson160'),prepScreen=screen('interviewPrep160'),qScreen=screen('interviewQuestions160'),talkScreen=screen('interviewTalk160'),draftScreen=screen('interviewDraft160');

  const lessons=[
    {id:'hero',title:'Герой и тема разговора',time:'7–10 мин',intro:'Интервью начинается не с вопроса, а с понимания, почему именно этот человек нужен материалу.',body:`<h3>Не «поговорить с интересным человеком»</h3><p>Сначала определите тему и журналистскую задачу. Затем спросите себя: <b>что именно этот герой знает, видел, сделал или пережил такого, что делает его важным собеседником?</b></p><div class="int160Rule">Известность героя сама по себе не заменяет тему. Хороший выбор героя объясняет, какую новую информацию читатель сможет получить именно из этого разговора.</div><p>До интервью полезно заранее отделить общедоступные сведения от того, что действительно нужно выяснить у человека.</p>`,q:'Какой принцип сильнее для выбора героя?',options:['Он известный, значит разговор автоматически будет интересным.','Понятно, какую новую информацию по теме можно получить именно у этого человека.','Нужно выбрать человека, о котором меньше всего информации в интернете.'],correct:1,feedback:'Да. Герой нужен не ради статуса, а ради доступа к опыту, знаниям и фактуре, которые работают на тему разговора.'},
    {id:'research',title:'Подготовка: изучить героя',time:'8–12 мин',intro:'Чем лучше вы знаете открытые факты, тем меньше времени тратите на вопросы, ответы на которые уже опубликованы.',body:`<h3>Перед разговором соберите базу</h3><ul><li>кто этот человек и чем занимается;</li><li>что уже говорил по вашей теме;</li><li>какие события, решения, проекты или конфликты связаны с темой;</li><li>какие факты требуют проверки или уточнения;</li><li>что в публичной информации остаётся непонятным.</li></ul><div class="int160Rule">Если ответ можно быстро найти в открытом источнике, вопрос должен хотя бы вести дальше: просить объяснить решение, мотивацию, последствия, личный опыт или неизвестные детали.</div>`,q:'Как лучше использовать найденный заранее факт?',options:['Повторить его герою как вопрос: «Правда ли, что вы…?»','Использовать как опору для более глубокого вопроса о причинах, деталях или последствиях.','Не читать ничего заранее, чтобы сохранить спонтанность.'],correct:1,feedback:'Верно. Исследование освобождает время разговора для новой информации, а не для пересказа уже известного.'},
    {id:'questions',title:'Вопросы: маршрут, а не анкета',time:'10–15 мин',intro:'Список вопросов нужен, но живое интервью не должно превращаться в чтение анкеты сверху вниз.',body:`<h3>Стройте разговор блоками</h3><p>Разделите тему на несколько смысловых блоков. В каждом подготовьте главные вопросы и возможные уточнения. Хороший вопрос обычно требует объяснения, примера, конкретной сцены, решения или аргумента.</p><ul><li>Избегайте длинного вступления, после которого герой уже забыл сам вопрос.</li><li>Не помещайте в один вопрос пять разных вопросов.</li><li>Не подсказывайте желаемый ответ.</li><li>Слушайте ответ: сильнейший следующий вопрос часто рождается прямо в разговоре.</li></ul><div class="int160Rule">План вопросов — страховка журналиста. Но если герой сказал важную новую вещь, важнее уточнить её, чем любой ценой перейти к вопросу № 8.</div>`,q:'Герой неожиданно сообщает важный новый факт. Что делать?',options:['Не отвлекаться от списка и задать следующий заготовленный вопрос.','Остановиться, уточнить факт, попросить детали и только потом вернуться к плану.','Сохранить факт, но не задавать уточнений, чтобы не давить на героя.'],correct:1,feedback:'Да. Интервью — живой разговор. Уточнение важной новой информации ценнее механического следования списку.'},
    {id:'talk',title:'Во время разговора',time:'8–12 мин',intro:'Главная работа интервьюера во время встречи — слушать, уточнять и удерживать тему.',body:`<h3>Не только задавайте — проверяйте ответ</h3><p>Если герой отвечает общо, просите пример. Если называет цифру — уточните источник или контекст. Если использует непонятный термин — попросите объяснить. Если противоречит тому, что говорил раньше, аккуратно обозначьте противоречие и дайте возможность ответить.</p><div class="int160Rule">Запись разговора не отменяет заметки. Отмечайте по ходу сильные фразы, новые факты, места для проверки и темы, к которым нужно вернуться.</div><p>Запись разговора должна быть согласована с собеседником там, где это требуется правилами вашей работы и контекстом беседы.</p>`,q:'Герой отвечает: «Это был очень сложный период». Какой следующий ход полезнее?',options:['Перейти дальше: оценка уже понятна.','Попросить конкретный пример: что именно происходило и в чём проявлялась сложность.','Спросить, был ли период скорее плохим или хорошим.'],correct:1,feedback:'Верно. Конкретизация превращает общую оценку в фактуру, с которой можно работать в материале.'},
    {id:'edit',title:'После разговора: собрать материал',time:'10–15 мин',intro:'Расшифровка — сырьё. Публикация требует отбора, проверки и ясной структуры.',body:`<h3>Что делать после интервью</h3><p>Сначала перечитайте разговор целиком и отметьте: новые факты, сильные объяснения, сцены и примеры, точные цитаты, спорные места и то, что нужно проверить. Затем соберите материал вокруг главной темы.</p><div class="int160Rule">Редактировать устную речь можно ради ясности, но нельзя менять смысл ответа или приписывать человеку формулировку, которой он не говорил. Существенно переписанная фраза безопаснее в косвенной речи.</div><p>Хорошая публикация не обязана содержать каждый заданный вопрос. Слабые повторы, технические уточнения и фрагменты вне темы можно убрать, если это не искажает разговор.</p>`,q:'Что делать с длинным ответом, смысл которого нужно сильно переписать?',options:['Оформить получившуюся красивую фразу прямой цитатой.','Передать смысл косвенной речью и не выдавать редакторскую формулировку за точную цитату.','Оставить весь ответ дословно независимо от читаемости.'],correct:1,feedback:'Да. Прямая цитата должна сохранять реальные слова героя; серьёзную редактуру безопаснее передавать косвенно.'}
  ];

  const countLessons=()=>lessons.filter(x=>I.lessons[x.id]).length;
  function stage(){if(I.submitted)return{title:'Черновик готов к редакторскому разбору',tag:'готово'};if((I.draft.text||'').trim())return{title:'Есть черновик интервью',tag:'черновик'};if((I.talk.transcript||'').trim())return{title:'Разговор проведён',tag:'разговор'};if((I.questions.main||'').trim())return{title:'Вопросы подготовлены',tag:'вопросы'};if((I.prep.hero||'').trim())return{title:'Герой выбран',tag:'подготовка'};return{title:'Начните с героя и темы',tag:'старт'}}
  function renderHub(){const s=stage();hub.innerHTML=`<div class="eye">Общая база · практика</div><div class="int160Hero"><div class="meta">Следующий формат после репортажа</div><h2>Интервью</h2><p>Выбрать героя не ради известности, подготовиться, провести реальный разговор, добыть новую фактуру и собрать публикацию.</p><div class="int160Tags"><span>герой</span><span>исследование</span><span>вопросы</span><span>уточнения</span><span>проверка</span></div></div><div class="int160Progress"><b>Матчасть: ${countLessons()} из ${lessons.length}</b><div class="meta" style="margin-top:5px">Перед реальным разговором особенно важны уроки про героя, исследование и вопросы.</div></div><div class="int160List">${lessons.map((l,i)=>`<button class="int160Card ${I.lessons[l.id]?'done':''}" data-int160-lesson="${l.id}"><div class="row" style="align-items:flex-start;gap:9px"><span class="int160Num">${i+1}</span><span style="flex:1"><b>${safe(l.title)}</b><small>${safe(l.intro)} · ${safe(l.time)}</small></span><span class="int160Status ${I.lessons[l.id]?'ok':''}">${I.lessons[l.id]?'готово':'открыть'}</span></div></button>`).join('')}</div><div class="int160Work"><div class="meta">Практическая работа</div><h3>Моё интервью</h3><p>${safe(s.title)}. Работа идёт в четыре шага: герой и задача → вопросы → реальный разговор → публикация.</p><button class="btn" data-int160-open-work>Продолжить работу →</button></div><div class="int160Actions"><button class="btn secondary" data-int160-route>← К моему маршруту</button></div>`}
  function openLesson(id){const l=lessons.find(x=>x.id===id);if(!l)return;const m=I.micro[id];lessonScreen.dataset.lesson=id;lessonScreen.innerHTML=`<div class="eye">Интервью · матчасть</div><div class="int160LessonHead"><div class="meta">${safe(l.time)}</div><h2>${safe(l.title)}</h2><p class="sub">${safe(l.intro)}</p></div><div class="int160Text">${l.body}</div><div class="int160Micro"><div class="meta">Быстрая проверка</div><h3>${safe(l.q)}</h3>${l.options.map((o,i)=>`<button class="int160Option ${m&&m.choice===i?(m.correct?'correct':'wrong'):''}" data-int160-micro="${i}">${safe(o)}</button>`).join('')}${m?`<div class="int160Feedback">${safe(m.correct?l.feedback:'Пока нет. Вернитесь к правилу выше и попробуйте ещё раз.')}</div>`:''}</div><div class="int160Actions">${m?.correct?'<button class="btn" data-int160-complete>Завершить урок</button>':''}<button class="btn secondary" data-int160-hub>← К модулю</button></div>`;go('interviewLesson160')}

  const pv=k=>safe(I.prep[k]||''),qv=k=>safe(I.questions[k]||''),tv=k=>safe(I.talk[k]||''),dv=k=>safe(I.draft[k]||'');
  function renderPrep(){prepScreen.innerHTML=`<div class="eye">Интервью · шаг 1 из 4</div><div class="int160StageHero"><div class="meta">До вопросов</div><h2>Герой и задача</h2><p>Сначала докажите себе, почему нужен именно этот человек и какую новую информацию должен принести разговор.</p></div><div class="int160Section"><h3>1. Герой</h3><div class="int160Field"><label>Кого вы хотите интервьюировать?</label><input class="input" data-int160-prep="hero" value="${pv('hero')}" placeholder="Имя, роль / профессия"></div><div class="int160Field"><label>Почему именно этот человек важен для темы?</label><textarea class="textarea" data-int160-prep="whyHero">${pv('whyHero')}</textarea></div><div class="int160Field"><label>Как вы попробуете договориться о разговоре?</label><textarea class="textarea" data-int160-prep="contactPlan" placeholder="Личный контакт, пресс-служба, соцсети, знакомство через организатора…">${pv('contactPlan')}</textarea></div></div><div class="int160Section"><h3>2. Тема и журналистская задача</h3><div class="int160Field"><label>О чём на самом деле будет разговор?</label><textarea class="textarea" data-int160-prep="topic">${pv('topic')}</textarea></div><div class="int160Field"><label>Что нового вы хотите узнать у героя?</label><textarea class="textarea" data-int160-prep="goal">${pv('goal')}</textarea><div class="int160Hint">Не «узнать о жизни», а конкретная неизвестная сторона темы, решение, опыт, мотив, конфликт, процесс или последствия.</div></div></div><div class="int160Section"><h3>3. Что уже известно</h3><div class="int160Field"><label>Какие факты о герое и теме вы уже нашли?</label><textarea class="textarea" data-int160-prep="known">${pv('known')}</textarea></div><div class="int160Field"><label>Где вы это проверили?</label><textarea class="textarea" data-int160-prep="sources" placeholder="Сайты, публикации, документы, прошлые интервью…">${pv('sources')}</textarea></div><div class="int160Field"><label>Что в открытой информации осталось непонятным?</label><textarea class="textarea" data-int160-prep="gaps">${pv('gaps')}</textarea></div></div><div class="int160Actions"><button class="btn" data-int160-save-prep>Сохранить подготовку</button><button class="btn secondary" data-int160-to-questions>Перейти к вопросам →</button><button class="btn secondary" data-int160-hub>← К модулю</button></div><div class="int160Saved">Подготовка сохраняется на этом устройстве.</div>`;go('interviewPrep160')}
  function collectPrep(){prepScreen.querySelectorAll('[data-int160-prep]').forEach(el=>I.prep[el.dataset.int160Prep]=el.value.trim());persist();return I.prep}const prepReady=p=>!!(p.hero&&p.whyHero&&p.topic&&p.goal&&p.known&&p.sources);

  function renderQuestions(){qScreen.innerHTML=`<div class="eye">Интервью · шаг 2 из 4</div><div class="int160StageHero"><div class="meta">До встречи</div><h2>Маршрут разговора</h2><p>Готовим блоки и главные вопросы, но оставляем место для уточнений, которые появятся из ответов героя.</p></div><div class="int160Section"><h3>1. Смысловые блоки</h3><div class="int160Field"><label>На какие 3–5 тем вы разделите разговор?</label><textarea class="textarea" data-int160-q="blocks" placeholder="Например: начало проекта → ключевое решение → конфликт → результат → что дальше">${qv('blocks')}</textarea></div></div><div class="int160Section"><h3>2. Главные вопросы</h3><div class="int160Field long"><label>Основные вопросы</label><textarea class="textarea" data-int160-q="main" placeholder="По одному вопросу на строку или с нумерацией">${qv('main')}</textarea></div><div class="int160Field"><label>Какие уточнения могут понадобиться?</label><textarea class="textarea" data-int160-q="followups" placeholder="Примеры, цифры, конкретные сцены, причины, последствия, кто ещё участвовал…">${qv('followups')}</textarea></div><div class="int160Field"><label>Какие неудобные или спорные места нужно обязательно прояснить?</label><textarea class="textarea" data-int160-q="hard">${qv('hard')}</textarea></div></div><div class="int160Section"><h3>Перед разговором</h3><label class="int160Check"><input type="checkbox" data-int160-q-check="notGoogle" ${I.questions.notGoogle?'checked':''}>Я не трачу основные вопросы на то, что уже легко находится в открытых источниках.</label><label class="int160Check"><input type="checkbox" data-int160-q-check="open" ${I.questions.open?'checked':''}>Большинство главных вопросов требуют развёрнутого ответа, а не «да / нет».</label><label class="int160Check"><input type="checkbox" data-int160-q-check="listen" ${I.questions.listen?'checked':''}>Я готов(а) отходить от списка и задавать уточнения по важным новым ответам.</label></div><div class="int160Actions"><button class="btn" data-int160-save-q>Сохранить вопросы</button><button class="btn secondary" data-int160-to-talk>Я провёл(а) интервью →</button><button class="btn secondary" data-int160-to-prep>← К герою и задаче</button></div>`;go('interviewQuestions160')}
  function collectQ(){qScreen.querySelectorAll('[data-int160-q]').forEach(el=>I.questions[el.dataset.int160Q]=el.value.trim());qScreen.querySelectorAll('[data-int160-q-check]').forEach(el=>I.questions[el.dataset.int160QCheck]=el.checked);persist();return I.questions}const qReady=q=>!!(q.blocks&&q.main&&q.followups&&q.notGoogle&&q.open&&q.listen);

  function renderTalk(){talkScreen.innerHTML=`<div class="eye">Интервью · шаг 3 из 4</div><div class="int160StageHero"><div class="meta">После встречи</div><h2>Разговор и фактура</h2><p>Сначала фиксируем, что реально сказал герой и что нового появилось. Красивый текст будет потом.</p></div><div class="int160Section"><h3>1. Встреча</h3><div class="int160Field"><label>Когда и где состоялся разговор?</label><input class="input" data-int160-talk="whereWhen" value="${tv('whereWhen')}"></div><label class="int160Check"><input type="checkbox" data-int160-talk-check="real" ${I.talk.real?'checked':''}>Это был реальный разговор с героем, а не придуманные ответы.</label><label class="int160Check"><input type="checkbox" data-int160-talk-check="recording" ${I.talk.recording?'checked':''}>Если разговор записывался, условия записи были понятны собеседнику.</label></div><div class="int160Section"><h3>2. Расшифровка / рабочая запись</h3><div class="int160Field long"><label>Вставьте расшифровку или подробные записи разговора</label><textarea class="textarea" data-int160-talk="transcript" placeholder="Можно вставить сырую расшифровку целиком. Пока ничего не украшайте.">${tv('transcript')}</textarea></div></div><div class="int160Section"><h3>3. Что добыли</h3><div class="int160Field"><label>Какие новые факты, объяснения или истории появились?</label><textarea class="textarea" data-int160-talk="newFacts">${tv('newFacts')}</textarea></div><div class="int160Field"><label>Какие точные фразы / цитаты особенно важны?</label><textarea class="textarea" data-int160-talk="quotes">${tv('quotes')}</textarea></div><div class="int160Field"><label>Что нужно проверить после разговора?</label><textarea class="textarea" data-int160-talk="verify">${tv('verify')}</textarea></div><div class="int160Field"><label>Что осталось недосказанным и требует дополнительного вопроса?</label><textarea class="textarea" data-int160-talk="followupAfter">${tv('followupAfter')}</textarea></div></div><div class="int160Actions"><button class="btn" data-int160-save-talk>Сохранить разговор</button><button class="btn secondary" data-int160-to-draft>Перейти к публикации →</button><button class="btn secondary" data-int160-to-q>← К вопросам</button></div>`;go('interviewTalk160')}
  function collectTalk(){talkScreen.querySelectorAll('[data-int160-talk]').forEach(el=>I.talk[el.dataset.int160Talk]=el.value.trim());talkScreen.querySelectorAll('[data-int160-talk-check]').forEach(el=>I.talk[el.dataset.int160TalkCheck]=el.checked);persist();return I.talk}const talkReady=t=>!!(t.whereWhen&&t.transcript&&t.newFacts&&t.quotes&&t.real);

  function renderDraft(){draftScreen.innerHTML=`<div class="eye">Интервью · шаг 4 из 4</div><div class="int160StageHero"><div class="meta">Публикация</div><h2>Соберите интервью</h2><p>Отберите то, что работает на главную тему. Не превращайте расшифровку в публикацию простым копированием.</p></div>${I.submitted?'<div class="int160Submitted"><b>Черновик сохранён для редакторского разбора</b><p>AI-разбор интервью подключим позже, после стабилизации методики жанра.</p></div>':''}<div class="int160Section"><h3>Текст</h3><div class="int160Field"><label>Рабочий заголовок</label><input class="input" data-int160-draft="title" value="${dv('title')}"></div><div class="int160Field"><label>Подводка: кто герой и зачем читателю этот разговор?</label><textarea class="textarea" data-int160-draft="lead">${dv('lead')}</textarea></div><div class="int160Field long"><label>Черновик публикации</label><textarea class="textarea" data-int160-draft="text" placeholder="Соберите интервью целиком. Можно оставить формат вопрос — ответ.">${dv('text')}</textarea></div></div><div class="int160Section"><h3>Самопроверка</h3><label class="int160Check"><input type="checkbox" data-int160-draft-check="theme" ${I.draft.theme?'checked':''}>После чтения понятно, о чём этот разговор, а не только кто герой.</label><label class="int160Check"><input type="checkbox" data-int160-draft-check="newInfo" ${I.draft.newInfo?'checked':''}>В публикации есть новая фактура, объяснения или примеры, полученные в разговоре.</label><label class="int160Check"><input type="checkbox" data-int160-draft-check="quotes" ${I.draft.quotes?'checked':''}>Прямые цитаты сохраняют смысл и реальные слова героя.</label><label class="int160Check"><input type="checkbox" data-int160-draft-check="facts" ${I.draft.facts?'checked':''}>Спорные факты, цифры, имена и должности проверены.</label><label class="int160Check"><input type="checkbox" data-int160-draft-check="cut" ${I.draft.cut?'checked':''}>Я убрал(а) повторы и технические фрагменты, не искажая смысл разговора.</label></div><div class="int160Actions"><button class="btn" data-int160-save-draft>Сохранить черновик</button><button class="btn secondary" data-int160-submit>Сохранить для редакторского разбора</button><button class="btn secondary" data-int160-to-talk>← К разговору</button></div><div class="int160Saved">Черновик сохраняется локально.</div>`;go('interviewDraft160')}
  function collectDraft(){draftScreen.querySelectorAll('[data-int160-draft]').forEach(el=>I.draft[el.dataset.int160Draft]=el.value.trim());draftScreen.querySelectorAll('[data-int160-draft-check]').forEach(el=>I.draft[el.dataset.int160DraftCheck]=el.checked);I.updatedAt=new Date().toISOString();persist();patchRoute();return I.draft}function draftReady(d){return !!(d.title&&d.lead&&d.text&&d.text.length>=300&&['theme','newInfo','quotes','facts','cut'].every(k=>d[k]))}
  function openWork(){if((I.draft.text||'').trim()||I.submitted)return renderDraft();if((I.talk.transcript||'').trim())return renderTalk();if((I.questions.main||'').trim())return renderQuestions();return renderPrep()}

  function patchRoute(){const route=document.getElementById('myRoute');if(!route)return;[...route.querySelectorAll('.route135Module')].forEach(card=>{if(card.querySelector('b')?.textContent?.trim()!=='Интервью')return;card.classList.add('int160Open');card.dataset.int160Open='1';const tag=card.querySelector('.tag');if(tag){const s=stage();tag.textContent=s.tag;tag.title=s.title}})}
  function patchReportHub(){const r=document.getElementById('reportCourse150');if(!r||r.querySelector('#int160Next'))return;const box=document.createElement('div');box.id='int160Next';box.className='int160Next';box.innerHTML='<div class="meta">Следующий практический формат</div><h3>Интервью</h3><p>После репортажа учимся готовиться к человеку: изучать героя, строить маршрут вопросов, слушать ответы и превращать реальный разговор в публикацию.</p><button class="btn secondary" data-int160-open>Открыть модуль →</button>';r.appendChild(box)}

  document.addEventListener('input',e=>{const p=e.target.closest('[data-int160-prep]');if(p){I.prep[p.dataset.int160Prep]=p.value;persist();return}const q=e.target.closest('[data-int160-q]');if(q){I.questions[q.dataset.int160Q]=q.value;persist();return}const t=e.target.closest('[data-int160-talk]');if(t){I.talk[t.dataset.int160Talk]=t.value;persist();return}const d=e.target.closest('[data-int160-draft]');if(d){I.draft[d.dataset.int160Draft]=d.value;I.submitted=false;persist()}});
  document.addEventListener('change',e=>{const q=e.target.closest('[data-int160-q-check]');if(q){I.questions[q.dataset.int160QCheck]=q.checked;persist();return}const t=e.target.closest('[data-int160-talk-check]');if(t){I.talk[t.dataset.int160TalkCheck]=t.checked;persist();return}const d=e.target.closest('[data-int160-draft-check]');if(d){I.draft[d.dataset.int160DraftCheck]=d.checked;I.submitted=false;persist()}});
  document.addEventListener('click',e=>{
    if(e.target.closest('[data-int160-open],[data-int160-open="1"]')){e.preventDefault();renderHub();go('interviewCourse160');return}
    if(e.target.closest('[data-int160-open-work]')){e.preventDefault();openWork();return}
    const l=e.target.closest('[data-int160-lesson]');if(l){e.preventDefault();openLesson(l.dataset.int160Lesson);return}
    const m=e.target.closest('[data-int160-micro]');if(m){e.preventDefault();const id=lessonScreen.dataset.lesson,x=lessons.find(v=>v.id===id);if(!x)return;const choice=Number(m.dataset.int160Micro);I.micro[id]={choice,correct:choice===x.correct};persist();openLesson(id);return}
    if(e.target.closest('[data-int160-complete]')){e.preventDefault();const id=lessonScreen.dataset.lesson;if(!I.micro[id]?.correct)return notify('Сначала выберите правильный ответ');I.lessons[id]=true;persist();renderHub();go('interviewCourse160');patchRoute();return}
    if(e.target.closest('[data-int160-hub]')){e.preventDefault();renderHub();go('interviewCourse160');return}
    if(e.target.closest('[data-int160-route]')){e.preventDefault();if(window.MMT_ROUTE_ENGINE?.sync)window.MMT_ROUTE_ENGINE.sync('interview');go('myRoute');setTimeout(patchRoute,0);return}
    if(e.target.closest('[data-int160-save-prep]')){e.preventDefault();collectPrep();notify('Подготовка сохранена');return}
    if(e.target.closest('[data-int160-to-questions]')){e.preventDefault();if(!prepReady(collectPrep()))return notify('Сначала заполните героя, тему, задачу, известные факты и источники');renderQuestions();return}
    if(e.target.closest('[data-int160-to-prep]')){e.preventDefault();renderPrep();return}
    if(e.target.closest('[data-int160-save-q]')){e.preventDefault();collectQ();notify('Вопросы сохранены');return}
    if(e.target.closest('[data-int160-to-talk]')){e.preventDefault();if(qScreen.classList.contains('active')&&!qReady(collectQ()))return notify('Сначала соберите блоки, основные вопросы, уточнения и подтвердите принципы подготовки');renderTalk();return}
    if(e.target.closest('[data-int160-to-q]')){e.preventDefault();renderQuestions();return}
    if(e.target.closest('[data-int160-save-talk]')){e.preventDefault();collectTalk();notify('Разговор сохранён');return}
    if(e.target.closest('[data-int160-to-draft]')){e.preventDefault();if(talkScreen.classList.contains('active')&&!talkReady(collectTalk()))return notify('Нужны реальный разговор, расшифровка, новые факты и важные цитаты');renderDraft();return}
    if(e.target.closest('[data-int160-save-draft]')){e.preventDefault();collectDraft();notify('Черновик сохранён');return}
    if(e.target.closest('[data-int160-submit]')){e.preventDefault();const d=collectDraft();if(!draftReady(d))return notify('Для редакторского разбора нужен полноценный черновик и завершённая самопроверка');I.submitted=true;I.submittedAt=new Date().toISOString();persist();renderDraft();patchRoute();notify('Интервью сохранено для редакторского разбора');return}
  });

  const obs=new MutationObserver(()=>{patchRoute();patchReportHub()});obs.observe(document.body,{subtree:true,childList:true});setTimeout(()=>{patchRoute();patchReportHub()},0);
})();
